### ISSUE TITLE
Error installing shadowsocks-local

### ISSUE THREAD

**Issue by abraaocaldas** [shadowsocks/shadowsocks-go#114]
When i try:  go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local

This error happens: 
go/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/encrypt.go:102: function ends without a return statement
go/src/github.com/shadowsocks/shadowsocks-go/shadowsocks/encrypt.go:283: function ends without a return statement

go version go1.0.2
ubuntu 14.04 x86_64

**Comment by cyfdecyf** [comment]
Please update to the latest version of Go.
