### ISSUE TITLE
请问ss-go服务端怎么查看日志？

### ISSUE THREAD

**Issue by BlueSplash** [shadowsocks/shadowsocks-go#120]
服务端是linux，没搜索到log之类的文件。。

**Comment by Alienero** [comment]
I think log information will print into std out. You can redirect std to a file.

**Comment by BlueSplash** [comment]
How to redirect std to a file?

**Comment by LibertyLocked** [comment]
`./shadowsocks-server & > ss.log`

**Comment by BlueSplash** [comment]
Thanks.

**Comment by haroldrandom** [comment]
Can I config the log level?

**Comment by arthurkiller** [comment]
@haroldrandom sure
