### ISSUE TITLE
请问是否支持自定义协议和协议混淆？

### ISSUE THREAD

**Issue by evilkong** [shadowsocks/shadowsocks-go#121]
rt， 目前没有看到和找到方法，请问什么时候mu版本可以支持自定义协议和协议混淆？

**Comment by lixingcong** [comment]
你应该找breakwa11。。。。ssr版本是ss的衍生版。

**Comment by evilkong** [comment]
breakwa11 没有搞go版，不过我也可以试试。。。

**Comment by lixin9311** [comment]
Currently, we do not have such plan, but any contribution is welcome.
