### ISSUE TITLE
cmd/shadowsocks-server/server.go: code error

### ISSUE THREAD

**Issue by jemyzhang** [shadowsocks/shadowsocks-go#127]
cmd/shadowsocks-server/server.go: main()

```
349		cmdConfig.Method = cmdConfig.Method[:len(cmdConfig.Method)-4]
```
should be change to:
```
		cmdConfig.Method = cmdConfig.Method[:len(cmdConfig.Method)-5]
```

另外有个疑点，不知道为什么NewCipher的时候，要特意将-auth参数去掉，难道ss内部还是没有真正实现ota，有或者是其他什么原因？

实际测试也是，如果不去除参数的话(piping xxxxx:42503<->8.8.8.8:53 ota=true connOta=true)，无法正常获取数据。

**Comment by cyfdecyf** [comment]
的确是个 bug，原先是 method-ota 这样的命名方式，后来改成其他实现通用的 method-auth 时漏掉了这里。

OTA 的文档里有提到：

> The chunk authentication is only applied for the packets sent from client-side shadowsocks.

所以只有 client 需要发送加入了 HMAC-SHA1 的信息的 chunk，而 server 向 client 段发送的数据中不需要这个。Cipher 标记 ota 表示发送数据时需要加入 HMAC-SHA1 信息，而这个只有 client 需要。

**Comment by teddysun** [comment]
请问一下，这段修正的代码尚未反映到二进制包里，何时编译好呢？
产生的影响就是在某些 VPS 是安装会出现Trace/breakpoint trap 现象。
