### ISSUE TITLE
Precompiled binarys file execute: Trace/breakpoint trap

### ISSUE THREAD

**Issue by teddysun** [shadowsocks/shadowsocks-go#130]
二进制文件在某些 VPS 下运行会出现 Trace/breakpoint trap 现象。
具体来说，就是在 Banwagonhost 的 VPS 下运行会出现的现象，如下显示版本号的命令：
补充：
shadowsocks-go 1.1.5
CentOS 6 x86_64
OpenVZ

```
[root@ss ~]# /usr/bin/shadowsocks-server --version
Trace/breakpoint trap
[root@ss ~]# echo $?
133
```

**Comment by lixin9311** [comment]
Refer to golang/go/issues/4447
