### ISSUE TITLE
Unsupported encryption method: chacha20-ietf 

### ISSUE THREAD

**Issue by netroby** [shadowsocks/shadowsocks-go#131]
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf
Unsupported encryption method: chacha20-ietf

https://shadowsocks.org/en/spec/cipher.html

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-go/blob/master/shadowsocks/encrypt.go#L15

除非上游加了支持，否则是不会有的

**Comment by v2ray** [comment]
欢迎使用 V2Ray: https://www.v2ray.com/zh_cn/chapter_02/protocols/shadowsocks.html

**Comment by lixin9311** [comment]
Fixed in #188
