### ISSUE TITLE
有办法禁用 ipv6 只用 ipv4 吗？

### ISSUE THREAD

**Issue by samurai00** [shadowsocks/shadowsocks-go#133]
现在连接服务端用的是 ipv4，但是浏览网站时，比如 google，会默认使用 ipv6，可能是我的 ipv6 又问题，老是让我输入验证码，很不方便。

所以请问有没有办法暂时禁用 ipv6？

**Comment by realpg** [comment]
并不是你的ipv6有问题
ipv6的机制，给你的就是/64的一个大块，你的服务器只使用其中的一个地址
当你建立代理服务器，产生大量来源明显不是一个设备的链接（cookies ua都不一样 很容鉴定出来）而共用一个IP地址 这是不正常的行为 所以google会让你输入验证码确认你不是机器模拟了很多连接

解决方案直接禁用ipv6，或者干脆删了你机器的ipv6路由 用 ip -6 route删了默认

**Comment by lijinpei** [comment]
通常server deamon的行为应该是根据监听的ip地址确定是ipv4/ipv6。但是在shadowsocks-go的shadowsocks-server中好像没有实现这个。
