### ISSUE TITLE
请问OTA的命令行开关是什么？以及配置文件的关键字

### ISSUE THREAD

**Issue by testcaoy7** [shadowsocks/shadowsocks-go#134]
1.15版的帮助输出并没有提到OTA：

-c string
    	specify config file (default "config.json")
  -core int
    	maximum number of CPU cores to use, default is determinied by Go runtime
  -d	print debug message
  -k string
    	password
  -m string
    	encryption method, default: aes-256-cfb
  -p int
    	server port
  -t int
    	timeout in seconds (default 300)
  -version
    	print version

还有如果要在配置文件里使用OTA的话，应该用什么关键字指定呢？

**Comment by Rememberli** [comment]
同问。

**Comment by cyfdecyf** [comment]
local 有 -A 选项可以开启 OTA，server 没有这个选项。server 默认行为是同时接受 OTA 和非 OTA 的 client，可以通过配置文件强制只接受 OTA client。

配置文件里在 encryption method 后加 `-auth` 即可，[例子](https://github.com/shadowsocks/shadowsocks-go/blob/master/config.json#L6)。
