### ISSUE TITLE
配置shadowsocks-go多用户遇到问题（已解决）

### ISSUE THREAD

**Issue by musicallok** [shadowsocks/shadowsocks-go#135]
你好！

我不明白你写的shadowsocks-go的多用户样本

于是我仿照shadowsocks-python的config.json来配置shadowsocks-go，失败了。

为什么在shadowsocks-go版本下运行这个config会失败呢？

{
    "server":"0.0.0.0",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "9283":"test01test",
        "9284":"test02test"
    },
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":false
}

**Comment by realpg** [comment]
shadowsocks-go 有一个demo config
你直接修改端口号和密码即可，其他不要管他
如果需要更多用户 多加一行

**Comment by musicallok** [comment]
@realpg  谢谢回复，我搞不懂shadowsocks-go怎么添加多用户
我重装了shadowsocks-go,我想添加一个端口为9001，密码为test02test的账户，请你指导
这是现在的config
{
    "server":"0.0.0.0",
    "server_port":8989,
    "local_port":1080,
    "password":"test01test",
    "method":"aes-256-cfb",
    "timeout":600
}

**Comment by realpg** [comment]
@musicallok 
请认真看我的回复，不要自以为是：
1. 代码里就有一份demo config
2. 修改那个demo config，只修改端口号和密码，如果需要更多，加一行

**Comment by musicallok** [comment]
@realpg 
谢谢批评指正，问题已经解决
我分享出来我的多用户config，不懂得人可以产考一下
{
"server": "0.0.0.0",
"local_port":1080,
"port_password":
{
"8989": "test01test",
"9000": "'test02test"
},
"timeout": 600,
"method": "aes-256-cfb"
}

**Comment by Tsuikiko** [comment]
@musicallok 楼主你好！我按照作者提供的多用户config文件 修改成你上面所提供的config，问题是，我发现只有第一个端口可以正常使用，而其他端口都无法联网，这是为何呢？config文件如下：
{
  "server": "XX.XX.XX.XX",
  "local_port":8070,
  "port_password":
  {
         "16006":"RemE314",
         "16007":"AvyE304",
         "16008":"YanE304",
  },
  "timeout": 600,
  "method": "aes-256-cfb"
}

这里就只有16006端口能正常使用了，找不出原因，望指点。

**Comment by musicallok** [comment]
@Tsuikiko 
有两个细节
"server": "XX.XX.XX.XX",  这行应该是"server": "0.0.0.0",
"16008":"YanE304", 多了","

**Comment by Tsuikiko** [comment]
@musicallok 谢谢你的回复。
关于第一点，就是说这里其实是直接填0.0.0.0，而不是服务器地址吗？

刚刚我试着按照你所指出的问题修改了一下，问题依旧，依然只有16006的端口能正常使用，其他端口一律无法联网。

这种情况是否需要开放监听端口呢？（看了一下其他教程里面有说，萌新不太懂是不是要这样解决）服务器程序为CentOS 6 X64。萌新望指点。

**Comment by Tsuikiko** [comment]
@musicallok 试着做了一下无用功，把前面的端口配置删除，留了一个16010和16011，然后重启SS-GO，发现都不能上网，感觉是与端口有关····遇到这种问题该怎么解决=，=？

**Comment by musicallok** [comment]
@Tsuikiko 
直接填写0.0.0.0

我没有设置监听端口,不知道是否有影响

问题依旧,会不会是有其它设置相互干扰呢?可以选择重装shadowsocks-go

或者请先备份你的config,再完全覆盖我上面的config样本到你的config
测试8989和9001两个端口,是否正常

我的也是CentOS 6 X64
多用户config正常运行

**Comment by Tsuikiko** [comment]
@musicallok 
好的，谢谢！
正在重装系统，其实也就装了个SS-GO，懒得麻烦还是重装了~
我先尝试一下从这里安装（之前一直装的是 秋水逸冰 的一键安装包，不知道是否会有影响·····）。再试试。

**Comment by musicallok** [comment]
@Tsuikiko 
我看你接近1小時沒回復
我就關閉了issue,我還以為你解決問題了

**Comment by Tsuikiko** [comment]
@musicallok 
额，刚刚在回家的路上=，=。萌新表示非常抱歉~-~。

**Comment by Tsuikiko** [comment]
@musicallok 
已找到解决方法，果然是因为防火墙问题，只需要去防火墙开放相应监听端口就行了。
谢谢楼主指导。

**Comment by huayuanp** [comment]
如何去防火墙开放相应的监听端口?

**Comment by HustWolfzzb** [comment]
请问 怎么去防火墙开放相应的端口呢？ 我待会也去尝试一下

**Comment by Tsuikiko** [comment]
@HustWolfzzb 
sudo ufw allow +端口号 即可。
eg. sudo  ufw allow  3306

**Comment by M2shad0w** [comment]
@HustWolfzzb 

centos6
```
iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport ${shadowsocksport} -j ACCEPT
                iptables -I INPUT -m state --state NEW -m udp -p udp --dport ${shadowsocksport} -j ACCEPT
                /etc/init.d/iptables save
                /etc/init.d/iptables restart
```
centos7

```
 firewall-cmd --permanent --zone=public --add-port=${shadowsocksport}/tcp
            firewall-cmd --permanent --zone=public --add-port=${shadowsocksport}/udp
            firewall-cmd --reload
```

**Comment by SS-user** [comment]
@M2shad0w 我按照centos7的语句输入，提示是Error: INVALID_PORT，请问这是什么情况
firewall-cmd --permanent --zone=public --add-port=${8989}/tcp
firewall-cmd --permanent --zone=public --add-port=${8989}/udp

**Comment by M2shad0w** [comment]
@SS-user 

firewall-cmd --permanent --zone=public --add-port=8989/tcp
firewall-cmd --permanent --zone=public --add-port=8989/udp

**Comment by SS-user** [comment]
@M2shad0w 谢谢，已经成功了

**Comment by edboffical** [comment]
https://github.com/edboffical/bsp

**Comment by ws1227** [comment]
在centos6 参考下边设置
端口开放（80改成自己想要开放的端口就可以了） 
# /sbin/iptables -I INPUT -p tcp --dport 9002 -j ACCEPT 

然后保存： 
# /etc/rc.d/init.d/iptables save 

重启防火墙 
# /etc/init.d/iptables restart

**Comment by chendachao** [comment]
ubuntu server下怎么开端口呢？
我尝试了各种大招，亦然不行。

firewall-cmd --permanent --zone=public --add-port=8388/tcp
firewall-cmd --permanent --zone=public --add-port=8388/udp
firewall-cmd --reload

============

sudo ufw allow 8388
sudo ufw allow 8388/tcp
sudo ufw allow 8388/udp

**Comment by arthurkiller** [comment]
@chendachao If u r using a vps server, u'd contact the service provider for firewall policy

**Comment by chendachao** [comment]
@arthurkiller, 好的，多谢

**Comment by MrWangwj** [comment]
> @musicallok
> 已找到解决方法，果然是因为防火墙问题，只需要去防火墙开放相应监听端口就行了。
> 谢谢楼主指导。

感谢大佬
