### ISSUE TITLE
go runtime error on server, very frequently.

### ISSUE THREAD

**Issue by ender-wan** [shadowsocks/shadowsocks-go#136]
i got this error everyday then server crashed, i'm using go 1.6.2 build server manually
is it my timeout set too long(600 second)?

goroutine 8 [IO wait, 753 minutes]:
net.(_pollDesc).Wait(0xc2080103e0, 0x72, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:84 +0x47
net.(_pollDesc).WaitRead(0xc2080103e0, 0x0, 0x0)
        /usr/lib/golang/src/net/fd_poll_runtime.go:89 +0x43
net.(_netFD).accept(0xc208010380, 0x0, 0x7fa188ec6a70, 0xc20802a858)
        /usr/lib/golang/src/net/fd_unix.go:419 +0x40b
net.(_TCPListener).AcceptTCP(0xc20802e038, 0x1f, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802e038, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/tcpsock_posix.go:244 +0x4c
main.run(0xc20802a6ac, 0x4, 0xc20802a6a0, 0xa, 0x0)
        /root/go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:280 +0x385
created by main.main
        /root/go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:378 +0x906

goroutine 17 [syscall, 753 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1

**Comment by lixin9311** [comment]
Outdated information.
If you encountered the same issue in recent build, please report again.
