### ISSUE TITLE
shadowsocks-go服务端支持udp relay 了吗？

### ISSUE THREAD

**Issue by lsnmx** [shadowsocks/shadowsocks-go#140]
@cyfdecyf 
怎么开启啊启动参数 -u 
shadowsocks-go version 1.1.5 不行啊

[root@www ~]# /home/go/bin/shadowsocks-server -p 33000 -k 123456 -m chacha20 -u
flag provided but not defined: -u
Usage of /home/go/bin/shadowsocks-server:
  -c string
        specify config file (default "config.json")
  -core int
        maximum number of CPU cores to use, default is determinied by Go runtime
  -d    print debug message
  -k string
        password
  -m string
        encryption method, default: aes-256-cfb
  -p int
        server port
  -t int
        timeout in seconds (default 300)
  -version
        print version

**Comment by lsnmx** [comment]
@lixin9311 @lucus

**Comment by lsnmx** [comment]
@cyfdecyf 大神从分支 @lixin9311 版本的支持一下吧，谢谢啦！

**Comment by lsnmx** [comment]
大神呢？

**Comment by seanchann** [comment]
https://github.com/bjjyd/shadowsocks-go  可以参考这个

**Comment by zinian** [comment]
@seanchann  这个编译。。。看 travis-ci 的编译过程 有点蒙
最后这个
$ go install ./mu
$ cd mu && go build

**Comment by seanchann** [comment]
这个已经修改了

**Comment by lsnmx** [comment]
@seanchann  几时更新到 go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
谢谢

**Comment by seanchann** [comment]
@lsnmx  针对原工程 整个都基本重写了，所以整个pr原作者可能不会允许通过！

**Comment by lsnmx** [comment]
@seanchann GO作者不是潜水不管了嘛？

**Comment by simonsmh** [comment]
@seanchann 有考虑加入tcpfastopen支持吗？

**Comment by dawei101** [comment]
up 一下

**Comment by seanchann** [comment]
@simonsmh  fastopen in todo list

**Comment by lsnmx** [comment]
GO SS都不更新了

**Comment by lixin9311** [comment]
Fixed in #72
