### ISSUE TITLE
Linux client not working

### ISSUE THREAD

**Issue by hitalex** [shadowsocks/shadowsocks-go#142]
I have deployed a ss server in a VPS. The ss client works fine on windows (which indicates that my ss server is working fine), but the go port and ss-libev of shadowsocks is not working on Linux(ubuntu 12.04, 64bit).

Anybody knows how to fix this ?

**Comment by hitalex** [comment]
The error msg is : Error No 104: connection reset by peer

**Comment by balbeleet** [comment]
connection reset by peer it's mean GFW in china

**Comment by lixin9311** [comment]
No further information received. Close.
