### ISSUE TITLE
shadowsocks-local支持pac模式么？

### ISSUE THREAD

**Issue by anyforever** [shadowsocks/shadowsocks-go#145]
shadowsocks-local支持pac模式么？
支持的话，配置格式是怎样的？

**Comment by KirinHuang** [comment]
我也有这个需求，gui版本都是支持的，为什么命令行的没有呢？

**Comment by penhauer-xiao** [comment]
我也有这个问题，命令行版本反而更强大了

**Comment by lixin9311** [comment]
Currently, we do not have such plan, but any contribution is welcome.
