### ISSUE TITLE
Minor behavior difference with python/libev version : getopt

### ISSUE THREAD

**Issue by lijinpei** [shadowsocks/shadowsocks-go#150]
Python/libev version uses getopt to parse command line argument, which behaves differently with go's flag package.

https://github.com/shadowsocks/shadowsocks/blob/master/shadowsocks/shell.py#L144
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/server.c#L1458
http://stackoverflow.com/questions/1714236/getopt-like-behavior-in-go

**Comment by lixin9311** [comment]
Not a bug.
