### ISSUE TITLE
Google DNS timeout

### ISSUE THREAD

**Issue by luohancfd** [shadowsocks/shadowsocks-go#151]
The server is set on a windows machine. But the machine couldn't connect to Google DNS: 8.8.8.8. Whenever the server is connected by a mobile client, the following report is presented.
![capture](https://cloud.githubusercontent.com/assets/6806720/18109891/68ab8208-6ee2-11e6-8c05-03289f69d40e.PNG)

Is there anyway to solve this?

**Comment by lixin9311** [comment]
Unreproducible issue.
Please check your network connection.
