### ISSUE TITLE
Block Connection to localhost

### ISSUE THREAD

**Issue by hamidfzm** [shadowsocks/shadowsocks-go#152]
In go port of shadowsocks there is no option to block ip like localhost or ... but there is an option available in python version:

https://github.com/shadowsocks/shadowsocks/wiki/Block-Connection-to-localhost

**Comment by lixin9311** [comment]
Please use iptables or other firewall application to achieve this function.

**Comment by hamidfzm** [comment]
Nice solution...
Very very help full.
Ty

**Comment by hamidfzm** [comment]
I've implemented a method to achieve this gaol
https://github.com/hamidfzm/Shadowsocks-Enterprise/blob/master/server/server.go#L119
