### ISSUE TITLE
ss-go怎么使用supervisor守护

### ISSUE THREAD

**Issue by Mistry-lee** [shadowsocks/shadowsocks-go#157]
最近不知道怎么的，服务端经常死掉，想用supervisor守护一下，但是普通版本的命令一直提示找不到服务，求go版本的supervisor  命令，哪位大神教一下，谢谢了。
比如下面的命令就不行：
[program:shadowsocks]
command=ss-server -c /etc/shadowsocks/config.josn
autostart=true
autorestart=true
user=nobody

**Comment by SCP-028** [comment]
把服务端的`ss-server`也改成绝对路径试试呢？

**Comment by duffy25** [comment]
config.json
