### ISSUE TITLE
shadowsock官方客户端支持吗？

### ISSUE THREAD

**Issue by qsfty** [shadowsocks/shadowsocks-go#158]
我用go客户端是可以正常使用vpn访问google的，但是当我使用shadowsock官方客户端就不能正常访问，是不支持，还是我的配置有问题呢？

![qq20160912-0](https://cloud.githubusercontent.com/assets/20365990/18432366/1ed63e84-7914-11e6-8297-5b39f70e7263.png)

**Comment by lixin9311** [comment]
使用的客户端版本是什么？
如何重现问题？
