### ISSUE TITLE
能提供一個 arm7 版本嗎?

### ISSUE THREAD

**Issue by carloshsu** [shadowsocks/shadowsocks-go#159]
我想在 Raspberry pi 3 上執行,能提供一個 arm7 版本嗎?

**Comment by simonsmh** [comment]
armhf 即可

**Comment by carloshsu** [comment]
爬了一下午的文,還是不太了解 "armhf  即可" 的意思. 我目前使用的OS image 是  http://mirror.centos.org/altarch/7/isos/armhfp/CentOS-Userland-7-armv7hl-Minimal-1603-RaspberryPi3.img.xz   
看起來似乎是armhfp, 和armhf 似乎有些關聯. 但仍無法直接使用 shadowsocks-go binary.

**Comment by lixin9311** [comment]
Please refer
https://golang.org/doc/install/source#environment
and
https://github.com/golang/go/wiki/WindowsCrossCompiling

**Comment by xtqxk** [comment]
[shadowsocks-local.zip](https://github.com/shadowsocks/shadowsocks-go/files/2255720/shadowsocks-local.zip)
你要的 arm7 版本.
