### ISSUE TITLE
How to install with the binaries 中国大陆怎么安装

### ISSUE THREAD

**Issue by kdlsw** [shadowsocks/shadowsocks-go#162]
I saw so much Chinese here in this forum, anyone has dealt the server in the mainland region? Github is banned by GFW (part of it I think), anyway, `go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server` command failed as `Couldn't resolve host 'github.com' while accessing https://github.com/shadowsocks/shadowsocks-go/info/refs` So I downloaded the binaries, but how to install it after using `tar -zxvf file.tar.gz` to unzip the folder? `shadowsocks-server` is still not working.

中文再说一遍。。。在大陆GitHub好像被封了，网页有时候也不能正常打开，所以，用go get指令自动下载ss的时候，发生了错误`Couldn't resolve host 'github.com' while accessing https://github.com/shadowsocks/shadowsocks-go/info/refs` 于是我下载了二进制的文件，但是用`tar -zxvf file.tar.gz`释放了下载的tar.gz之后应该怎么操作，输入`shadowsocks-server`仍然显示未知指令。请指教，谢谢

**Comment by orvice** [comment]
terminal设置下http_proxy https_proxy
