### ISSUE TITLE
JSON-RPC

### ISSUE THREAD

**Issue by Conver** [shadowsocks/shadowsocks-go#164]
It would be great to see a JSON-RPC service in this, which would make it much easier for web developers to add and/or remove users on the fly

**Comment by fuyufjh** [comment]
Suggest to keep consistent with shadowsocks-python and libev, even it's really a bad protocol, 😆 

https://github.com/shadowsocks/shadowsocks/wiki/Manage-Multiple-Users#protocol

**Comment by arthurkiller** [comment]
#193  fixed . closed
