### ISSUE TITLE
macOS(10.12) shadowsocks with i/o timeout

### ISSUE THREAD

**Issue by nevernet** [shadowsocks/shadowsocks-go#165]
2016/10/09 22:49:21 available remote server xxx.xxx.xxx.xxx:12050
2016/10/09 22:49:21 starting local socks5 server at :7070 ...
2016/10/09 22:49:32 socks handshake: socks version not supported
1970/01/01 08:00:00 socks handshake: read tcp 127.0.0.1:7070->127.0.0.1:52517: i/o timeout
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x3cf2e1f8a1a pc=0x11adb0]

tried version: 1.1.1 and 1.1.5 (downloaded from release page<precompiled version>)

please advice

**Comment by nevernet** [comment]
i have been using shadowsocks python version to instead :)

**Comment by devil1995** [comment]
@nevernet share me a copy ....

**Comment by bigtan** [comment]
其实这个问题是golang带来的，自己用最新版的golang编译一下就行了。

**Comment by nevernet** [comment]
@devil1995 just navigate to https://github.com/shadowsocks/shadowsocks or try:
```
pip install shadowsocks
```

@bigtan yes, i have been solved it.

**Comment by devil1995** [comment]
@nevernet thinks...I'll try..by the way ....give me a email :>....
