### ISSUE TITLE
my process paniced in server.go, line 83

### ISSUE THREAD

**Issue by amoylan** [shadowsocks/shadowsocks-go#168]
The code in line 83 : `"host = string(buf[idDm0 : idDm0+buf[idDmLen]])"`
Since the idDm0 is 2, idDm0+buf[idDmLen] is no more than 257, it should not panic while the buf length is 270. But it occured with the message "slice out of length".

**Comment by amoylan** [comment]
I mistaked the condition just now, but my process paniced more than twice with the message "panic in server.go:83 slice out of length"

**Comment by andwxh** [comment]
Hi, I found your case is the same reason caused issue #179 . Will update my PR #183 to fix this later.

**Comment by amoylan** [comment]
@andwxh Good job, thanks a lot, I have read the reason you replied in #183, and I will take care of this in my work.
