### ISSUE TITLE
where is the server log file? 请问服务器的日志文件在哪里？

### ISSUE THREAD

**Issue by kdlsw** [shadowsocks/shadowsocks-go#170]
After running the server, in background, the verbose feedback is not visiable, only leaves a process. Does anyone know how to bring this process and verbose feedback to the front? Or, there supposed to be a log file isn't it? I searched, could not find any, anyone knows where it is? Thanks

运行服务器之后，如果放置到后台的话，服务器的信息反馈就看不见了，只有在进程里能看到这个服务器在跑，有没有什么办法能再把它弄到前台来？或者，应该有个服务器日志的log文件吧，我大概搜索了一下，没发现，请问这个文件在哪里呢？谢谢！

**Comment by lixin9311** [comment]
如果用的是自带的deb包，应该位于 `/var/log/shadowsocks`
如果自己写的脚本，那么检查一下你的脚本输出重定向。
