### ISSUE TITLE
不能通过shadowssocks-android访问

### ISSUE THREAD

**Issue by docooler** [shadowsocks/shadowsocks-go#171]
我在服务器端用的是shadowsocks-go server.客户端使用的android客户端。访问失败。请问有没有做适配计划！或者客户端那边的协议有没有想关文档。scale代码没有学过。看起来比较费力
提示log如下；

^Croot@docooler:~/workspace/go/bin# cat config.json
{
    "server":"127.0.0.1",
    "server_port":8388,
    "local_port":1080,
    "password":"**********!",
    "method": "aes-128-cfb-auth",
    "timeout":600
}
root@docooler:~/workspace/go/bin# ./server -c config.json -d
2016/11/01 04:04:39 server listening port 8388 ...
2016/11/01 04:05:50 creating cipher for port: 8388
[DEBUG] 04:05:50 new client 223.104.4.48:21438->128.199.185.147:8388
2016/11/01 04:05:50 error getting request 223.104.4.48:21438 128.199.185.147:8388 addr type 8 not supported
[DEBUG] 04:05:50 closed pipe 223.104.4.48:21438<->

**Comment by lixin9311** [comment]
检查OTA设置
