### ISSUE TITLE
Windows automatic proxy fails socks handshake

### ISSUE THREAD

**Issue by lichray** [shadowsocks/shadowsocks-go#172]
Platform: Windows 10 1607
Version: 1.1.5

WinHTTP AutoProxy now always performs proxy type detection, and shadowsocks-go rejects it.

Reproduce:
Do "Manual proxy setup" in Windows 10, then try Edge, receiving "socks version not supported" errors in shadowsocks-local.

**Comment by lixin9311** [comment]
Recommend using other client programs other than the go version.
We are currently focusing on the server side.

I plan to rewrite an client for it.
