### ISSUE TITLE
用shadowsocks翻墙后申请谷歌邮箱的问题

### ISSUE THREAD

**Issue by hwp994108018** [shadowsocks/shadowsocks-go#173]
本人是谷歌的重度用户，每天都要在谷歌泡个7、8个小时，而且经常需要申请谷歌邮箱用于各种业务，但是用搬瓦工+shadowsocks 翻墙后，每次申请谷歌邮箱都需要电话验证，而现在谷歌服务器不知怎么了，换了不知换多少个电话号码，都提示：“您的号码不能用于验证”。以前用goagent一天申请2个都不需要，所以想问一下，怎样才可以直接申请到谷歌邮箱而不需要电话验证？

**Comment by navigaid** [comment]
把年龄设置为14周岁以下，或者直接取消谷歌账户与电话号码的关联 @hwp994108018

**Comment by hwp994108018** [comment]
@navigaid 你好，谢谢，我试试。为什么用搬瓦工+shadowsocks 翻墙后，每次 “申请谷歌邮箱” 都需要电话验证呢？我也换过机房以改变IP地址，但还是要电话验证。

**Comment by SuperSuperSuperSuper5** [comment]
@hwp994108018 你可以联系我邮箱我帮你申请，我的这边可以申请

**Comment by hwp994108018** [comment]
非常感谢你的好意，不过我经常性要申请谷歌邮箱的，不太好老麻烦你，而且你那申请IP和登录IP不一样的话，是要电话验证的？！
