### ISSUE TITLE
only listens on IPv6, not IPv4

### ISSUE THREAD

**Issue by MrRyanHoffman** [shadowsocks/shadowsocks-go#174]
I can't get my server to listen on IPv4, only IPv6.  Is there a trick to get IPv4 working?

[myID@CLGRTESTSRVR01 bin]$  ./shadowsocks-server -d  > log &
[1] 10576
[myID@CLGRTESTSRVR01 bin]$ more log
2016/11/22 00:59:55 server listening port 8388 ...
[myID@CLGRTESTSRVR01 bin]$ more config.json
{
    "server_port":8388,
    "password":"barfoo!",
    "local_address":"192.168.0.1",
    "timeout":600
}
[myID@CLGRTESTSRVR01 bin]$ netstat -an | grep 8388
tcp6       0      0 :::8388                 :::*                    LISTEN
[myID@CLGRTESTSRVR01 bin]$

**Comment by MrRyanHoffman** [comment]
Update: SOLVED?
Just discovered that tcp6 sockets can function for both v4 and v6

**Comment by lixin9311** [comment]
tcp6 sockets can function for both v4 and v6
