### ISSUE TITLE
关于安全性问题

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-go#176]
https://github.com/breakwa11/shadowsocks-rss/issues/448

如以上链接所示，此问题是否能修复？

**Comment by Remonli** [comment]
@cyfdecyf  已经很久没有提交代码了。

**Comment by andwxh** [comment]
这个问题无法被彻底解决，因为ss的协议就是这样的。但是可以去掉代码中对ATYP字节的&F，这样能让探测的最高枚举次数从8次变为256次，但是这个也是一个设计问题，就看维护者的想法了。
另外如果可能的话增加iv cache也不错，命中cache则抛弃，这样攻击者需要耗尽cache才能进行下一次枚举，枚举次数会极大提升。

**Comment by lixin9311** [comment]
Fixed in develop branch
