### ISSUE TITLE
期望可以支持PAC模式

### ISSUE THREAD

**Issue by penhauer-xiao** [shadowsocks/shadowsocks-go#178]
shadowsocks-qt5 或Windows shadowsocks client 很强大，支持PAC模式或全局模式，可以切换本地PAC,或服务器PAC； 为什么shadowsocks-go 等等命令行模式反而没有界面客户端做得强大

**Comment by lixin9311** [comment]
I recommend using other client programs other than go version.
Currently, we do not have such plan, but any contribution is welcome.
