### ISSUE TITLE
shadowsocks-server panics

### ISSUE THREAD

**Issue by chenchun** [shadowsocks/shadowsocks-go#179]
shadowsocks-server panics :(
```
2016/12/22 13:44:19 error getting request 123.118.211.57:53937 128.199.190.121:443 addr type 11 not supported
2016/12/22 13:44:20 error getting request 123.118.211.57:53939 128.199.190.121:443 addr type 15 not supported
2016/12/22 13:44:20 error getting request 123.118.211.57:53941 128.199.190.121:443 verify one time auth failed, iv=[249 219 5 87 197 39 195 230 101 20 34 208 188 62 138 242] key=[84 8 205 185 52 121 127 247 239 0 194 191 229 82 124 125] data=[116 45 130 156 18 60 28 92 164 245 44 210 2 188 22 139 184 102 105]
2016/12/22 13:44:20 error getting request 123.118.211.57:53945 128.199.190.121:443 addr type 10 not supported
panic: runtime error: slice bounds out of range

goroutine 36363 [running]:
panic(0x5dda60, 0xc82000e0b0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.getRequest(0xc820234280, 0x671500, 0x0, 0x0, 0xc82001f500, 0x0, 0x0)
        /go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:70 +0xdf9
main.handleConnection(0xc820234280, 0xc820234200)
        /go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:138 +0x3f8
created by main.run
        /go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:296 +0x8d6
```

**Comment by AcceptSocket** [comment]
Encountered the same problem:
```
panic: runtime error: slice bounds out of range

goroutine 45992 [running]:
panic(0x5d7bc0, 0xc82000e0a0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
main.getRequest(0xc820479a90, 0x66a500, 0x0, 0x0, 0xc820323d00, 0x0, 0x0)
        /Users/cyf/local/go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:83 +0xd33
main.handleConnection(0xc820479a90, 0xc820479a00)
        /Users/cyf/local/go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:138 +0x3f8
created by main.run
        /Users/cyf/local/go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server/server.go:296 +0x8d6
```

**Comment by andwxh** [comment]
I have just occurred the same issue.

**Comment by andwxh** [comment]
Panic was happened at this line:
`if _, err = io.ReadFull(conn, buf[reqStart:reqEnd]); err != nil {`

I found that max value of _reqStart_ is **2** and max value of _reqEnd_ is **270**. Meanwhile the length of _buf_ is 270. Hence it is not possible to panic here.

Anyone have ideas?

**Comment by andwxh** [comment]
**Update:**
I found the reason. Will sending PR later.

**Comment by andwxh** [comment]
Before this PR merged, you can use:
go get github.com/andwxh/shadowsocks-go/cmd/shadowsocks-server
to fix this issue.

**Comment by andwxh** [comment]
@chenchun @mmzhi @AcceptSocket @amoylan

Hey guys, I found there is another place which byte overflows by reading issue #168 , so it means my last PR not fix this completely.

I have just updated my PR #183 .

If you have used my fork version to fix this panic, please rebuild your server by using:

> go get github.com/andwxh/shadowsocks-go/cmd/shadowsocks-server

**Comment by lixin9311** [comment]
@andwxh Thank you for your contribution.

**Comment by andwxh** [comment]
Hi, @lixin9311 do you have privilege to merge this to master? I think this is quite series, because a potential attacker will not need anything just enumerate ATYP byte with the domain length byte for no more than 1024 times will let the server crash. (256 times for ATYP, and 3 * 256 times for domain length)

**Comment by lixin9311** [comment]
@andwxh I'm running some tests for UDP relay and new cipher method, if everything works fine, I will make a new release.

**Comment by andwxh** [comment]
@lixin9311 I've seen your commits, thank you for your great work!
