### ISSUE TITLE
不能在golang 1.6.3里面编译。

### ISSUE THREAD

**Issue by sndnvaps** [shadowsocks/shadowsocks-go#182]
出现错误如下：
go get github.com/golang/crypto/blowfish
package github.com/golang/crypto/blowfish
	imports github.com/golang/crypto/blowfish
	imports github.com/golang/crypto/blowfish: code in directory /home/travis/gopath/src/github.com/golang/crypto/blowfish expects import "golang.org/x/crypto/blowfish"

**Comment by lixin9311** [comment]
编译时确保良好的网络环境能够获取golang.org下的包
