### ISSUE TITLE
设置多端口无效，求解！！！

### ISSUE THREAD

**Issue by 10N99** [shadowsocks/shadowsocks-go#185]
试了各种方法还是只有1过端口可以用。

**Comment by andwxh** [comment]
https://github.com/shadowsocks/shadowsocks-go/blob/master/sample-config/server-multi-port.json

**Comment by 10N99** [comment]
还是不可以阿

**Comment by bigtan** [comment]
@10N99 没问题的，你自己设置有误吧

**Comment by 10N99** [comment]
@bigtan 可以帮我看一下吗 你有微信或者QQ吗 发我一下。

**Comment by weithink** [comment]
@10N99  你要设置你vps 的防火墙的

**Comment by lixin9311** [comment]
Not an issue of shadowsocks.
