### ISSUE TITLE
Issues with release 1.2.1

### ISSUE THREAD

**Issue by Contextualist** [shadowsocks/shadowsocks-go#190]
1. When I checked its version with `-version`, the output is `1.2.0` instead of `1.2.1`;
2. Please compile to statically linked binaries, refering to [build.sh](../blob/master/script/build.sh).

**Comment by lixin9311** [comment]
Sorry for that, I forgot to change the version number in the code.

Everything should work well except the version number printing.
For the link problem, it's a default behavior of `gc` compiler, I have recompiled the binaries with `CGO_ENABLED=0` and uploaded again.
If you care about this, please redownload the binary files from the release page.

Thank you for the report.
