### ISSUE TITLE
Change log into zap log by Uber-go

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/shadowsocks-go#191]
We have test many go logs and find that Zap get the best performance in all log lib.
With zap log, the access log can be staged with a very small cost.
Bad thing is Zap should be a dependency for shadowsocks-go.
Whats your opinion.

**Comment by arthurkiller** [comment]
@lixin9311  I can help this with a PR if necessary

**Comment by lixin9311** [comment]
I'm planning to reconstruct the whole project, and rewrite the client program.
So I'm afraid we do not have any plan to introduce new features and improvement to the current version.

Anyway, it's a good suggestion, I will try it in my new version.
And I'll keep this open.

**Comment by arthurkiller** [comment]
Awesome. Is there any schedule for this milestone? I'd like to make some PR

**Comment by lixin9311** [comment]
Unfortunately, we do not have a schedule. I work on this project only as a side work.

Currently, it is hard to use the code in other projects, and so is the server/client program.
As a result, it's hard to make improvements for server/client.

I'm planning to reconstruct the shadowsocks package, make it more like a library, friendly to be used in other projects.

If you have any idea and suggestion, welcome to open an issue and share it.

**Comment by arthurkiller** [comment]
I will keep watching on it. Thank you
