### ISSUE TITLE
开启OTA后，速度反而更慢

### ISSUE THREAD

**Issue by Aniark** [shadowsocks/shadowsocks-go#194]
坐标QOS严重地区，未开启OTA前油管只有1000kbps左右，开启后，降到500kbps左右

是否OTA已经不能抵抗GFW，反而成为了更强的特征？

**Comment by lixin9311** [comment]
用libev版本试试？如果你用了udp的话 油管用了QUIC 慢是正常

**Comment by Aniark** [comment]
@lixin9311 libev版经过测试速度在1000kbps左右，udp和ota都是开启的

但是go开启ota的话，速度会显著受影响，开启udp倒是没那么明显

**Comment by lixin9311** [comment]
你用的是什么版本的？
有时间我会调查一下

**Comment by Aniark** [comment]
@lixin9311 shadowsocks-go 1.2.1 操作系统Ubuntu14.04

**Comment by Galaxy0419** [comment]
OTA建议不要使用，隐患更大，早在之前libev已经弃用，请使用AEAD加密

**Comment by arthurkiller** [comment]
新版本已经去掉了OTA支持，TODO 会加入 AEAD

**Comment by Aniark** [comment]
@arthurkiller  我现在用的就是最新的版本（1.2.1)，ota还在，aead也没有……

**Comment by arthurkiller** [comment]
@Aniark #129   AEAD还在我的测试分支，还有点bug 没解决。不过貌似大多数客户端也还没支持aead

**Comment by Aniark** [comment]
@arthurkiller win客户端，Android端都支持aead了

**Comment by arthurkiller** [comment]
@Aniark  OK,那我这边加快进度，争取节后可以用。不过不知道这个项目目前是谁在维护，PR也没人鸟我

**Comment by Aniark** [comment]
@arthurkiller 最后一次更新是由 @lixin9311 所提交的，也许你可以问问他？

**Comment by arthurkiller** [comment]
@Aniark  嗯，我在联系了，谢谢你

**Comment by Galaxy0419** [comment]
@Aniarkios客户端的shadow rocket也已经支持，现在已经全平台支持了

**Comment by Aniark** [comment]
@arthurkiller 话说，现在支持了aead的ss-go，和这个项目 https://github.com/shadowsocks/go-shadowsocks2 有什么不同呢？

**Comment by arthurkiller** [comment]
新项目跟这个项目是独立的，新项目是rio新开发的，这个是旧项目在进行一次重构和优化升级

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by Galaxy0419** [comment]
@arthurkiller新版本大概什么时候出来？

**Comment by arthurkiller** [comment]
新版本已经提pr了，aead还有点bug 在本地分支，预计节后

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
