### ISSUE TITLE
New implementation

### ISSUE THREAD

**Issue by riobard** [shadowsocks/shadowsocks-go#198]
A new Go port of Shadowsocks has been forked into Shadowsocks organization

https://github.com/shadowsocks/go-shadowsocks2

This implementation is a clean rewrite. I believe it lays a better foundation for future improvement than the legacy Go port. 

As suggested by @madeye here https://github.com/shadowsocks/shadowsocks-org/issues/38#issuecomment-277497449, I'm inviting @lixin9311 to discuss if there is chance of collaboration.

**Comment by arthurkiller** [comment]
awesome work
