### ISSUE TITLE
Incorrect socks5 handshake buf size?

### ISSUE THREAD

**Issue by dunjut** [shadowsocks/shadowsocks-go#199]
cmd/shadowsocks-local/local.go  line 51:

`buf := make([]byte, 258)`

--

According to [socks5](https://tools.ietf.org/html/rfc1928) protocol, the initial client greeting message follows a structure shown as below:

                   +----+----------+----------+
                   |VER | NMETHODS | METHODS  |
                   +----+----------+----------+
                   | 1  |    1     | 1 to 255 |
                   +----+----------+----------+

The 1 byte NMETHODS field results in max 255 METHODS, thus max length of the initial greeting message will be 257 (1+1+255) bytes.

Not sure am I missing anything that's 1 byte?

**Comment by arthurkiller** [comment]
maybe nothing special... just one more byte... LOL

that's a good question
