### ISSUE TITLE
1.2.1的releases是64位linux版的吗

### ISSUE THREAD

**Issue by moqiaoduo** [shadowsocks/shadowsocks-go#201]
RT，上面没标不确定

**Comment by teddysun** [comment]
Yes, it is.
for x86_64 only

**Comment by teddysun** [comment]
我自行编译了当前最新版 Linux 的 64 和 32 位二进制文件，下载链接如下：
64 bit：
http://dl.teddysun.com/shadowsocks/shadowsocks-server-linux64-1.2.1.gz
32bit：
http://dl.teddysun.com/shadowsocks/shadowsocks-server-linux32-1.2.1.gz

欢迎下载使用。

**Comment by arthurkiller** [comment]
closed
