### ISSUE TITLE
cow不支持shadowsocks-go版本吗？

### ISSUE THREAD

**Issue by ZAntony** [shadowsocks/shadowsocks-go#203]
我有两台server，一台在杭州，一台vps在美国，开始的时候我配置二级代理使用ss(本地并未安装shadowsock)，服务端安装的是go版本的ss。但是一直显示 “addr type <number> not supported” ，看您在其他的地方回复的是密码不正确，我确认后没问题。

客户端： ubuntu 16.04
server： centos7

**Comment by bigtan** [comment]
支持的，cow依赖shadowsocks-go

**Comment by vy0b0x** [comment]
是不是两边加密算法不一致？

**Comment by arthurkiller** [comment]
如果还有问题,可以继续反馈

closed
