### ISSUE TITLE
监听到ipv6?

### ISSUE THREAD

**Issue by xdeng** [shadowsocks/shadowsocks-go#204]
2017/02/17 15:54:14 listening udp port 9999
2017/02/17 15:54:14 error listening udp port 9999: listen udp [::]:9999: socket: An address incompatible with the requested protocol was used.
2017/02/17 15:54:14 server listening port 9999...
2017/02/17 15:54:15 creating cipher for port: 9999

为什么监听 ipv6的 udp 失败了？  系统是win 2003 如果说不支持ipv6 为啥tcp没报错。

**Comment by arthurkiller** [comment]
not supported yet
