### ISSUE TITLE
Precompiled Binaries For Windows

### ISSUE THREAD

**Issue by MRACHINI** [shadowsocks/shadowsocks-go#206]
can you give Precompiled Binaries for windows in the releases please

**Comment by elico** [comment]
@MRACHINI Still need the binaries?

**Comment by arthurkiller** [comment]
@MRACHINI try this
`  ENV GOOS=Windows go build `

**Comment by MRACHINI** [comment]
I always compile, but the availability of pre-compiled binaries could save me some time.

Thank you for the replies

**Comment by arthurkiller** [comment]
Later will add the CI for auto release. I really want do this but I’m not the admin of this repo

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
@elico Yes dude,
>BUT I’m NOT the admin of this repo

**Comment by elico** [comment]
@arthurkiller I will try to see if I can work on a jenkins CI local instance that will build and package at each update.

**Comment by arthurkiller** [comment]
@elico Awesome, and I will try to add this in my PR, Still merging in progress yet
