### ISSUE TITLE
打开谷歌的时候会报错

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-go#208]
找不到 ipv6.google.com 的服务器 DNS 地址。

**Comment by Galaxy0419** [comment]
关闭ipv6可以解决，求改进

**Comment by bigtan** [comment]
try https://github.com/shadowsocks/go-shadowsocks2

**Comment by Galaxy0419** [comment]
或者客户端开启ipv6转发也可以解决。

**Comment by GeeFans** [comment]
我也遇到这样的情况了，每次都要验证。感觉还是一个人用较好，多人使用肯定会出现这种情况？

**Comment by GeeFans** [comment]
再或者，在服务端禁用监听ipv6?

**Comment by arthurkiller** [comment]
这个不是用的人多的原因，而是谷歌针对云服务器做的策略，云服务器ip都会被拦截恶意流量

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by GeeFans** [comment]
不是吧？最近才出现验证，以前没碰到过，跳转到ipv6.google.com验证 多半还是说明ipv6的原因。

**Comment by arthurkiller** [comment]
closed. Plz report in new issue
