### ISSUE TITLE
哥们，你的那个next 分支有计划么？

### ISSUE THREAD

**Issue by arthurkiller** [shadowsocks/shadowsocks-go#211]
@lixin9311  我在看你的next 分支，你这个分支啥时候merge？？？我想给你推个PR 也没法搞呢。有计划么？

**Comment by lixin9311** [comment]
他们最近不是搞了一个2么，可以看看那个。缺的那个包应该是因为github的默认分支不对。最近一些新特性我不准备跟进了，还是参照新版设计吧。
2017年4月2日(日) 18:39 Arthur-Lee <notifications@github.com>:

**Comment by arthurkiller** [comment]
@lixin9311  哈哈，那我能不能用你的分支，然后改进了推push 呢？

**Comment by lixin9311** [comment]
可以，保留commit签名就行
2017年4月2日(日) 19:01 Arthur-Lee <notifications@github.com>:

**Comment by arthurkiller** [comment]
@lixin9311  好的，那有问题可以发你的gmail 不~
