### ISSUE TITLE
在linode部署了，twitter能访问，google无法访问，咋回事？

### ISSUE THREAD

**Issue by fprint** [shadowsocks/shadowsocks-go#212]
如题。部分网站能访问，另一些又无法访问。debug也没有什么错误信息。

**Comment by fprint** [comment]
然后把dns缓存也清了，twitter也无法访问了。go版的是还需要啥特殊的设置么？

**Comment by arthurkiller** [comment]
@fprint  有没有确认你的vps 能否访问那些网站，以防万一？

**Comment by fprint** [comment]
已经搞定，我估摸着可能是换了内核的关系。重装后就好了。结贴。
