### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by AkumaZhang** [shadowsocks/shadowsocks-go#213]
import cycle not allowed
package github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
	imports bytes
	imports errors
	imports runtime
	imports runtime/internal/atomic
	imports unsafe
	imports runtime
import cycle not allowed
package github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
	imports github.com/shadowsocks/shadowsocks-go/shadowsocks
	imports net
	imports runtime/cgo
	imports runtime/cgo
[root@akuma ~]# go version
go version go1.6.3 linux/amd64

**Comment by arthurkiller** [comment]
new version will launch in this mounth，all will be fixed

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by AkumaZhang** [comment]
thanks everything
