### ISSUE TITLE
如何把服务器端的某一端口的流量发送给ss处理再传送给客户端？

### ISSUE THREAD

**Issue by Edelwiess** [shadowsocks/shadowsocks-go#214]
没错，我就是想用shadowssocks来代理电驴的流量。获得电驴highID。
vps是自己的。
比如我电驴设置的端口是12345端口，我需要把服务器12345端口收到的数据全部发送给ss处理后再发给ss的出口比如8308.

**Comment by arthurkiller** [comment]
>我需要把服务器12345端口收到的数据全部发送给ss处理后再发给ss的出口比如8308.
这个不能理解，这是什么样的需求？我理解的是增加一个callback？@Edelwiess

**Comment by Edelwiess** [comment]
就是我需要用电驴软件，这个软件需要一个公网ip的端口来与外界通信，比如12345端口，现在我需要把本地127.0.01的12345端口的流量都经过ss代理再发送到服务器的12345端口再发出去。

**Comment by arthurkiller** [comment]
@Edelwiess  
对于ss来说，只需要把你的所有请求都代理就好。  大概理解了下，你是想反过来用。就是说不需要socks5了，而是固定的出口规则？ss listen 指定的端口，然后直接定向到你的本地相同的端口？
我感觉这是把ss反过来用啊？
          client         <---->             ss            <---->          resource
Donkey :12345        <-----              ss   listen   :12345    <----------->     Resource

**Comment by Edelwiess** [comment]
谢谢，就是这个意思。但是本地是windows的。。。

**Comment by Edelwiess** [comment]
而且没有公网ip，估计开不了ss吧

**Comment by arthurkiller** [comment]
是的，这个会比较尴尬，所以建议是你自己在vps 上搭建一个反向代理比较好

**Comment by arthurkiller** [comment]
closed
