### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-go#215]
2017/04/09 17:28:09 creating cipher for port: 8388                                                2017/04/09 17:28:09 error getting request 101.90.126.41:20107 138.68.9.231:8388 addr type 12 not supported                                         2017/04/09 17:28:14 error getting request 101.90.126.41:20108 138.68.9.231:8388 addr type 11 not supported
2017/04/09 17:28:19 error getting request 101.90.126.41:20109 138.68.9.231:8388 addr type 14 not supported

**Comment by arthurkiller** [comment]
@Galaxy0419  could you plz give more infomations about this problem?

**Comment by armaab** [comment]
@Galaxy0419 Maybe your password was incorrect.
