### ISSUE TITLE
运行几天后无限报错然后自行kill进程，主要错误如下

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-go#216]
2017/04/10 15:32:43 error getting request 116.238.129.105:34734 138.68.9.231:8388 read tcp 138.68.9.231:8388->116.238.129.105:34734: i/o timeout
2017/04/11 03:11:38 error getting request 101.90.255.185:63360 138.68.9.231:8388 EOF
2017/04/11 02:09:11 error connecting to: www.hcaijin.com:80 dial tcp: lookup www.hcaijin.com on [2001:4860:4860::8888]:53: read udp [2604:a880:2:d0::16bd:7001]:35194->[2001:4860:4860::8888]:53: i/o timeout

**Comment by arthurkiller** [comment]
@Galaxy0419  建议使用tcp ，性能更好，另外新版本正在开发，马上就可以用新版了，bug都修了

**Comment by lixin9311** [comment]
这是关于golang内部请求dns的问题，请把你的系统版本以及ss的编译参数告诉我们

**Comment by arthurkiller** [comment]
closed
