### ISSUE TITLE
在gce部署了之后，还需要啥特殊设置么？

### ISSUE THREAD

**Issue by fprint** [shadowsocks/shadowsocks-go#217]
因为gce的虚拟机ip是内网地址，然后分配了一个外网地址，web服务的话，外网正常访问，但是部署了ss-go后，外网无法访问，好奇怪。

**Comment by cielpy** [comment]
需要在后台设置允许 ss 端口外网访问

**Comment by fprint** [comment]
重新部署后，问题消失了，关帖。
