### ISSUE TITLE
请教服务端如何从1.1.5升级到最新

### ISSUE THREAD

**Issue by lsnmx** [shadowsocks/shadowsocks-go#220]
服务器上GO SS服务端是1.1.5，想升级到最新，执行 
go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
还是没有升级上去，求升级代码CentOS 7

**Comment by arthurkiller** [comment]
@lsnmx  #219  是最新版，已经提交了，等merge 了更新下就好了

**Comment by arthurkiller** [comment]
@lsnmx  到文件夹下面执行 go install 就行了

**Comment by arthurkiller** [comment]
```
cd github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
go install
```

**Comment by lsnmx** [comment]
@arthurkiller 原来升级是要加执行 go install 啊，我试试吧，第一次安装就
cd github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server 
就成功了，不知道升级方式

**Comment by lsnmx** [comment]
@arthurkiller  不行，求指导啊，实在升级不上去，麻烦了

[root@iZ627wr5dn7Z ~]# cd /home/go/bin
[root@iZ627wr5dn7Z bin]# go install
can't load package: package .: no buildable Go source files in /home/go/bin
[root@iZ627wr5dn7Z bin]# /home/go/bin/shadowsocks-server -version
shadowsocks-go version 1.1.5
[root@iZ627wr5dn7Z bin]# cd github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
-bash: cd: github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server: No such file or directory
[root@iZ627wr5dn7Z bin]# go get github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
[root@iZ627wr5dn7Z bin]# /home/go/bin/shadowsocks-server -version
shadowsocks-go version 1.1.5
[root@iZ627wr5dn7Z bin]# go install
can't load package: package .: no buildable Go source files in /home/go/bin
[root@iZ627wr5dn7Z bin]# /home/go/bin/shadowsocks-server go install
must specify both port and password
[root@iZ627wr5dn7Z bin]# /home/go/bin/go install
-bash: /home/go/bin/go: No such file or directory
-bash: QQ258771866qq!: command not found
[root@iZ627wr5dn7Z bin]# cd github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
-bash: cd: github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server: No such file or directory
[root@iZ627wr5dn7Z bin]# go install
can't load package: package .: no buildable Go source files in /home/go/bin

**Comment by lsnmx** [comment]
@arthurkiller  大神我上执行记录了，麻烦看看，升级不到去

**Comment by arthurkiller** [comment]
@lsnmx  你要到那个目录下执行

**Comment by arthurkiller** [comment]
首先要找到go path 才行。你要配置了$GOPATH 。
应该是类似目录： /home/go/src/github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
你看一下能不能cd 这个目录

**Comment by arthurkiller** [comment]
@lsnmx  在这个目录下执行 go install ，他就会把二进制文件放到你的/go/bin 目录下.或者你直接编译，或者下载二进制包，然后解压放到 /usr/bin 下面就行

**Comment by Contextualist** [comment]
@lsnmx 试试任何目录下执行 `go get -u github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server`，这会更新本地代码库和依赖并重新编译安装。

**Comment by lsnmx** [comment]
@Contextualist  谢谢大神，
go get -u github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
可以升级了，-u这命令没有官方标示啊，只找到以下的，难怪我怎么折腾都升级不去啊

Usage of /home/go/bin/shadowsocks-server:
  -c string
    	specify config file (default "config.json")
  -core int
    	maximum number of CPU cores to use, default is determinied by Go runtime
  -d	print debug message
  -k string
    	password
  -m string
    	encryption method, default: aes-256-cfb
  -p int
    	server port
  -t int
    	timeout in seconds (default 300)
  -version
    	print version

@arthurkiller 谢谢，你的方法不行，太复杂了，GO环境变量肯定设置了，要不然也无法从源码编译啊
以下应该是GO环境了
修改/etc/profile文件，最后加入
export PATH=$PATH:/root/go/bin
export GOPATH=/home/go
export GOROOT=/root/go

**Comment by lsnmx** [comment]
@arthurkiller @Contextualist 借帖子弱弱的请教一下，这条
/home/go/bin/shadowsocks-server -c config.json  这条启动命令
一定要先 cd /home/go/bin ，执行
/home/go/bin/shadowsocks-server -c config.json 才能生效？
config.json配置文件已经搞好端口，密码~~等了，能不能实现直接就
/home/go/bin/shadowsocks-server -c config.json 跑起来监听的是config.json的数据

[root@iZ627wr5dn7Z ~]# /home/go/bin/shadowsocks-server -c config.json
must specify both port and password
[root@iZ627wr5dn7Z ~]# 


 cd /home/go/bin
/home/go/bin/shadowsocks-server -c config.json

[root@iZ627wr5dn7Z bin]# /home/go/bin/shadowsocks-server -c config.json
2017/04/27 02:15:39 server listening port 30001 ...

**Comment by arthurkiller** [comment]
嗯，我决定加一个部署脚本。。方便下小白。。

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
@lsnmx  新的版本将会加入dockerfile 支持，可以一键部署支持docker 的服务端

**Comment by lsnmx** [comment]
@arthurkiller  这个问题能不能在任何目录执行 shadowsocks-server -c config.json 
借帖子弱弱的请教一下，这条
/home/go/bin/shadowsocks-server -c config.json 这条启动命令
一定要先 cd /home/go/bin ，执行
/home/go/bin/shadowsocks-server -c config.json 才能生效？
config.json配置文件已经搞好端口，密码~~等了，能不能实现直接就
/home/go/bin/shadowsocks-server -c config.json 跑起来监听的是config.json的数据

[root@iZ627wr5dn7Z ~]# /home/go/bin/shadowsocks-server -c config.json
must specify both port and password
[root@iZ627wr5dn7Z ~]#

cd /home/go/bin
/home/go/bin/shadowsocks-server -c config.json

[root@iZ627wr5dn7Z bin]# /home/go/bin/shadowsocks-server -c config.json
2017/04/27 02:15:39 server listening port 30001 ...

**Comment by arthurkiller** [comment]
@lsnmx  只要bin文件在$PATH下面就可以

**Comment by lsnmx** [comment]
@arthurkiller  指导一下吧，以下我要怎么修改，谢谢大神
GO环境
修改/etc/profile文件，最后加入
export PATH=$PATH:/root/go/bin
export GOPATH=/home/go
export GOROOT=/root/go

**Comment by arthurkiller** [comment]
哥们听我一句，你要是想容易点，就下载release的包，tar xf 解压，然后直接运行
不用这么费劲

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by lsnmx** [comment]
@arthurkiller 哥们我也知道方便，源码编译方便升级啊

**Comment by arthurkiller** [comment]
你先学学linux基础知识吧

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
closed
