### ISSUE TITLE
客户端多server配置

### ISSUE THREAD

**Issue by ycz0926** [shadowsocks/shadowsocks-go#224]
请问下，在客户端配置中指定多个server配置时，local连接server时，是怎样的连接策略呢？可否根据连接是否超时自动切换线路呢？

**Comment by arthurkiller** [comment]
新的版本中加入了根据server latency 自动优选的功能，merge 之后可以用。

**Comment by ycz0926** [comment]
好的，thanks

**Comment by ldaochen** [comment]
问下现在master分支中有根据server latency 自动优选的功能吗？

**Comment by arthurkiller** [comment]
在我提的PR里面有，还没merge

**Comment by ldaochen** [comment]
Pull Request for reconstruction  这个PR吗？

**Comment by arthurkiller** [comment]
没，在我本地的分支，这个都没合并，我也懒得merge了。要是需要我就弄一下

**Comment by arthurkiller** [comment]
可以看看是什么需求，是按照延迟来排序，还是轮询server 做负载均衡，还是有更多的需求

**Comment by ldaochen** [comment]
按延迟或者轮询都可以，可以加一个选项来决定采用哪个均衡策略吗？

**Comment by arthurkiller** [comment]
好，有空我就加上

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by ldaochen** [comment]
@arthurkiller 谢谢！

**Comment by ycz0926** [comment]
现在使用时遇到了另一个问题，系统是mac，多次关闭显示器再次开启后，程序会崩溃，猜测是代码开启了过多的协程所致，希望fix下

**Comment by arthurkiller** [comment]
收到，新版本会进行针对性测试

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
added
