### ISSUE TITLE
请问windows下如何开启api?

### ISSUE THREAD

**Issue by 749860493** [shadowsocks/shadowsocks-go#225]
shadowsocks-server --manager-address 127.0.0.1:6001
这条命令在哪运行？

**Comment by arthurkiller** [comment]
在命令行

**Comment by arthurkiller** [comment]
win + R
cmd
cd 到目录下
执行命令

**Comment by 749860493** [comment]
在目录下用命令行执行我是知道的，直接执行ss.exe -c config.json -u shadowsocks-server --manager-address 127.0.0.1:6001这样对吗？

**Comment by arthurkiller** [comment]
嗯，目前版本可能是这样的

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by 749860493** [comment]
但是这样执行以后没有任何额外提示信息，在ss manager网页上用管理员帐号修改ss信息，节点服务器没有反应，主控端和节点端都没有任何错误提示，貌似是节点端的ss manager 跟ss对接不上，可能是api没有成功开启？

**Comment by arthurkiller** [comment]
不理解你想表达的含义。go ss的server不支持管理

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
win用户建议用客户端 c#那个

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
closed
