### ISSUE TITLE
Unable To Connect After Upgrade

### ISSUE THREAD

**Issue by zQueal** [shadowsocks/shadowsocks-go#227]
I just upgraded my server to the go client--however, I get a plethora of `verify one time auth failed` and `addr type XX not supported` errors.

`config.json`

```json
{
	"port_password": {
		"8000": "item fillip tattoo twinge",
		"8001": "cutups buckles fraught archer"
	},
	"method": "aes-128-cfb",
	"local_port": 1080,
	"timeout": 600
}
```

Additionally I run the server with `shadowsocks-server -u -d -c config.json`. 

Here are the settings I use for the android client;

|Property|Value|
|:--|:--|
|IP|Server IP|
|Port|8000|
|Password|`item fillip tattoo twinge`|
|method|`AES-128-CFB`|

or `ss://aes-128-cfb:item fillip tattoo twinge@{IP}:8000`

---------------------

Redacted log file;

```log
2017/05/28 04:39:46 error getting request local_ip:41516 server_ip:8000 addr type 9 not supported
[DEBUG] 04:39:46 closed pipe local_ip:41516<->
[DEBUG] 04:39:46 new client local_ip:41518->server_ip:8000
2017/05/28 04:39:46 error getting request local_ip:41518 server_ip:8000 addr type 8 not supported
[DEBUG] 04:39:46 closed pipe local_ip:41518<->
2017/05/28 04:39:46 error getting request local_ip:41493 server_ip:8000 unexpected EOF
[DEBUG] 04:39:46 closed pipe local_ip:41493<->
2017/05/28 04:39:46 error getting request local_ip:41512 server_ip:8000 addr type 0 not supported
[DEBUG] 04:39:46 closed pipe local_ip:41512<->
[DEBUG] 04:39:46 new client local_ip:41513->server_ip:8000
2017/05/28 04:41:46 error connecting to: unknown_ip:61107 dial tcp unknown_ip:61107: getsockopt: connection timed out
[DEBUG] 04:41:46 closed pipe local_ip:41458<->unknown_ip:61107
2017/05/28 04:48:37 error getting request local_ip:41638 server_ip:8000 verify one time auth failed, iv=[108 111 153 81 251 139 93 164 39 40 11 191 49 31 155 181] key=[77 87 31 75 125 63 11 166 210 103 246 4 249 81 33 189] data=[20 201 178 52 13 70 209 196 31 235 242 201 105 143 118 69 129 160 110]
[DEBUG] 04:48:37 closed pipe local_ip:41638<->[c9b2:340d:46d1:c41f:ebf2:c969:8f76:4581]:41070
[DEBUG] 04:48:37 new client local_ip:41641->server_ip:8000
```

Any ideas?

-----------------

I created a blank `config.json` file (containing `{ }`) and tried with these variables;

    shadowsocks-server -d -k {password} -m aes-128-cfb -p 8000 -t 600 -u -c test_config.json

Seems to work fine. Leads me to believe it may be the multi-port support which is bugging out? I've also tried the above command with `aes-128-cfb-auth` and I get output in the log which contains `ota=false connOta=false`. This seems wrong as well.

------------------------

I _purposefully_ changed the password in the Android client to ensure it was __incorrect__. The errors in the logs are similar to what I get when I try to use `port_password` in my config.

**Comment by arthurkiller** [comment]
@zQueal  Bro , you'd better abandon the OTA cause this feature has been tagged as depreciated

**Comment by arthurkiller** [comment]
log says seems your socks proxy going wrong. try without the OTA and choose make sure u have seem configuration on both client and server

**Comment by arthurkiller** [comment]
Here I got a new version for this repo to help with bug fixing and new feature. But still waitting for merge yet. U can use ss-go2 instead also

**Comment by arthurkiller** [comment]
@zQueal

**Comment by lixin9311** [comment]
will be fixed in next version
