### ISSUE TITLE
请问什么时候进行更新？

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-go#228]
AEAD加密到现在还没有实现，还有tcp fast open记得之前有某位大神有开发过AEAD请问什么时候merge？

**Comment by ky0ncheng** [comment]
![](http://wx1.sinaimg.cn/mw1024/6d9bd6a5gy1fhyc0ioyryj20n20nk79y.jpg)

就你屁事多

**Comment by terasum** [comment]
不行了笑死我了🤣

**Comment by liuxyc** [comment]
哈哈，不带这样的

**Comment by suhaotian** [comment]
哈哈哈...

**Comment by lixin9311** [comment]
you made my day, dude.
