### ISSUE TITLE
请问有没有接口可以获取用户请求了哪个url？

### ISSUE THREAD

**Issue by rafw** [shadowsocks/shadowsocks-go#229]
也就是记录上网记录，谢谢。

**Comment by arthurkiller** [comment]
ss目的是匿名代理，不应该记录这些

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
不过，新版里面的log 的info 级别会有所有的访问记录

**Comment by rafw** [comment]
也就是说，当前Github最新原版就已经在日志里包含了访问记录了，对吗？

**Comment by bradyjoestar** [comment]
I think maybe we can develop such a function ,let the server's owner to define how to use.

**Comment by lixin9311** [comment]
please develop such functions on your own
