### ISSUE TITLE
ubnuntu 16.04 脚本跑起来了，但是翻不了墙。。

### ISSUE THREAD

**Issue by laoyouzi** [shadowsocks/shadowsocks-go#232]
买了vps，配置好config.json， 但是翻不了墙，跪求大神指点一下，谢谢

**Comment by arthurkiller** [comment]
@laoyouzi 贴一下配置，不用贴密码端口。

然后在你的vps上ping一下google
```
ping www.google.com
``` 
看看能不能通

如果ss有错误日志也贴一下，不然无法分析

**Comment by laoyouzi** [comment]
可以ping 通

**Comment by laoyouzi** [comment]
@arthurkiller sorry，我试了一下www.google.com ping 不同的，但是没有错误日志啊

**Comment by arthurkiller** [comment]
把日志打开。另外，阿里云是没法翻墙的。访问不了谷歌，基本可以说明你的梯子搭在墙里面了。。

**Comment by laoyouzi** [comment]
@arthurkiller  我的启动脚本日志正常，在/var/log/xxxxx 下没看到日志。。。不知道在哪看日志，sorry，麻烦指一下

**Comment by arthurkiller** [comment]
@laoyouzi  加上 -d 参数，然后重定向到文件。 tail -f 看

**Comment by laoyouzi** [comment]
@arthurkiller  
![image](https://user-images.githubusercontent.com/20438144/27761205-16d1b25c-5e8a-11e7-9afb-aaa682281610.png)

**Comment by arthurkiller** [comment]
@laoyouzi  你的客户端用的是什么？

**Comment by arthurkiller** [comment]
@laoyouzi  服务端似乎没有收到客户端的请求，这种情况应该看一下客户端的日志

**Comment by laoyouzi** [comment]
@arthurkiller 很尴尬，我没有装客户端，我直接是在ubuntu 火狐浏览器访问的，必须用客户端吗

**Comment by arthurkiller** [comment]
as server 和 ss client之间使用的是本身是自己的自有协议，ss client使用socks5协议与其他客户端协商，你的浏览器一般只支持http协议，因此你需要ss客户端，同时也需要http转socks5代理

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by laoyouzi** [comment]
@arthurkiller 非常感谢你，我准备装 OpenWrt

**Comment by arthurkiller** [comment]
嗯嗯，也可以试试ss python那个，应该是实现最完整的了

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by laoyouzi** [comment]
@arthurkiller  我试了一下，看他们也有这个问题但是没有解决，所以我就装了go版本的
 ![image](https://user-images.githubusercontent.com/20438144/27761556-c6171e68-5e90-11e7-9f2f-1dc1aec9e55f.png)

**Comment by arthurkiller** [comment]
这个是因为你使用姿势不对造成的

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by laoyouzi** [comment]
@arthurkiller  我没有一键安装，我是按 readmine  用pip上安装的

**Comment by muzea** [comment]
看着像是你客户端填写的服务器信息错了，截图为啥不全一点呢？关键信息打个码也可以

**Comment by lixin9311** [comment]
not a bug

**Comment by arthurkiller** [comment]
@lixin9311  Comming back? Congratulation!
