### ISSUE TITLE
可以出一个ssr 的go 语言客户端吗.

### ISSUE THREAD

**Issue by xiahuaijia** [shadowsocks/shadowsocks-go#233]
树莓派只能安装 go语言的版本.

please/

**Comment by arthurkiller** [comment]
ss 跟 ssr不是一个东西

**Comment by teddysun** [comment]
如果服务器端安装了 go 版，那么客户端请使用原版 Shadowsocks for Windows 客户端：
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by xiahuaijia** [comment]
我在用的是go语言 ss的客户端 . 
因为需要把ss转成socks 5 . http 给其他设备使用.
现在问题是 ss被精准检测需要换ssr 
但ssr 只有C# 和 lib的版本. 
 而我的树莓派是CentOS 7用不了py版本
只有go语言支持.
希望能有一个ss 带混淆的go语言版

**Comment by teddysun** [comment]
树莓派是 CentOS 7 用不了 py 版本还可以用 libev 版本，libev 也是支持 AEAD 的。
go 版开发几乎已经陷入停滞状态了……

**Comment by xiahuaijia** [comment]
我先试试 吧 当时ss 的libev  版本是缺少编译环境.

**Comment by xiahuaijia** [comment]
https://github.com/avege/avege
go语言版ssr项目地址

**Comment by arthurkiller** [comment]
ss被精准检测？什么意思？？


现在go的aead还没开发完

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by teddysun** [comment]
@arthurkiller go 的 AEAD 支持，我看到你的代码那里还注释掉了。辛苦了，请继续加油！
另外，现在 SS 在运营商后台只能被识别成 TCP 流量，然后会显示连接的服务器 IP

**Comment by xiahuaijia** [comment]
也就是go语言的 SS 没有像ssr 的作者说的那么恐怖会被断宽带 和 写保证书?

**Comment by arthurkiller** [comment]
其实我有创建了一个slack，可以进入讨论，关于设计和需求的建议

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by teddysun** [comment]
@arthurkiller 有 Telegram 群组的话，不妨发出来。slack 在国内用的并不多吧。

**Comment by arthurkiller** [comment]
thx ，现在在休假，回来会尽快推动这个落地

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by imMMX** [comment]
>  现在问题是 ss被精准检测需要换ssr

there is no evidence that ss package has been identified. you should have a mind of your own.

**Comment by lixin9311** [comment]
emm
please read the reply of imMMX.
