### ISSUE TITLE
centos6更新系统报ERROR

### ISSUE THREAD

**Issue by yb3616** [shadowsocks/shadowsocks-go#235]
是搬瓦工KVM架构的VPS，开了bbr，Kernel: x86_64 Linux 4.12.0-1.el6.elrepo.x86_64

Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ndchost.com
 * elrepo-kernel: repos.lax-noc.com
 * extras: mirror.sjc02.svwh.net
 * ius: mirrors.kernel.org
 * updates: yum.tamu.edu
Resolving Dependencies
--> Running transaction check
---> Package shadowsocks-libev.x86_64 0:2.5.5-1.el6 will be updated
---> Package shadowsocks-libev.x86_64 0:3.0.8-2.el6 will be an update
--> Processing Dependency: mbedtls for package: shadowsocks-libev-3.0.8-2.el6.x86_64
--> Processing Dependency: udns for package: shadowsocks-libev-3.0.8-2.el6.x86_64
--> Processing Dependency: libev for package: shadowsocks-libev-3.0.8-2.el6.x86_64
--> Finished Dependency Resolution
Error: Package: shadowsocks-libev-3.0.8-2.el6.x86_64 (librehat-shadowsocks)
           Requires: udns
Error: Package: shadowsocks-libev-3.0.8-2.el6.x86_64 (librehat-shadowsocks)
           Requires: mbedtls
Error: Package: shadowsocks-libev-3.0.8-2.el6.x86_64 (librehat-shadowsocks)
           Requires: libev
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by arthurkiller** [comment]
U should repost this issue under ss_libev

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
