### ISSUE TITLE
为什么老是提示must specify both port and password呢

### ISSUE THREAD

**Issue by lzgmxd** [shadowsocks/shadowsocks-go#237]
正常在用，就是什么都不能动，所有的命令都是这个信息

**Comment by arthurkiller** [comment]
因为你配置的不对呀 @lzgmxd

**Comment by lzgmxd** [comment]
可是能正常用啊

**Comment by arthurkiller** [comment]
你用的master么？这个还不太了解。你可以试一下我fork的分支，实现的更好一点，应该会pull 到这里 @lzgmxd

**Comment by Shadowhack0419** [comment]
@arthurkiller 请问您的版本实现AEAD了么？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arthurkiller** [comment]
@Shadowhack0419  之前就实现完成了，不过有小bug，还在本地测试修改。然而这2周有事情特别忙，预计2周内merge dev

**Comment by arthurkiller** [comment]
closed
