### ISSUE TITLE
Will there be perfomance degredation when it reaches max client connections?

### ISSUE THREAD

**Issue by gin1314** [shadowsocks/shadowsocks-go#241]
hi im getting this line on my running shadowsocks server

```
2017/08/21 07:56:12 Number of client connections reaches 100
2017/08/21 07:56:12 Number of client connections reaches 100
```

how do i increase number of connection limit? or is there any? Any advice would be greatly appreciated, Thanks :)

**Comment by arthurkiller** [comment]
@gin1314 don't care about this, and will remove this warning log in the feature

**Comment by lixin9311** [comment]
Just some info for the administrators.
