### ISSUE TITLE
Packaging shadowsocks-go for CentOS 7, Ubuntu 16.04 and Debian 8+9

### ISSUE THREAD

**Issue by elico** [shadowsocks/shadowsocks-go#247]
I have been working for quite some time on packaging services for:
- CentOS 7
- RHEL 7
- Ubuntu 16.04 
- Debian 8+9
- OpenSUSE Leap
- Others

I have a set of build nodes locally that I can build, package and publish ShadowSocks-Go.
With what from the list I am starting?(The easiest for me is CentOS 7)

**Comment by arthurkiller** [comment]
Perhaps do this via CI is better
For example,  package the packet when tag the release

**Comment by elico** [comment]
@arthurkiller It is a task for CI but I am not sure how to set it up with jenkins or how to check if there is a new tag in the branch using the git command.
I have seen a sketch at:
https://medium.com/this-happened-to-me/monitor-a-git-branch-for-changes-749c8c3ccae2

but I was wondering if you might know how to monitor tags remotely?
Or if you have a better idea on how to integrate the project using CI?

**Comment by arthurkiller** [comment]
Github developer prefer TravisCI more, it is easy to use and friendly to github. All you need is a config file to trigger the build and release

Example here

’’’
deploy:
  provider: releases
  api_key:
    secure:  your secure key here
  file:
  - 'dist/mac-osx.tar.gz'
  - 'dist/linux-x64.tar.gz'
  - 'dist/linux-ia32.tar.gz'
  skip_cleanup: true
  on:
    repo: arthurkiller/repo name here
    tags: true
’’’

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
https://docs.travis-ci.com/user/deployment/releases/

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by elico** [comment]
@arthurkiller The main two options are:
- github trigger
- active periodic tests\checks of the github tree state

I will look into them both.

**Comment by arthurkiller** [comment]
closed
