### ISSUE TITLE
Linux 客户端支持全局+PAC GFWList方式代理吗？

### ISSUE THREAD

**Issue by penhauer-xiao** [shadowsocks/shadowsocks-go#252]
Windows是可以自己编辑GFWList 增加被墙的网站； 很方便， 比如拉代码时，国外有的代码网站就拉不了，配一下GFWList文件加一行，马上就可以拉对应的网站代码了，很方便。
https://www.shadowsocks.org/en/spec/Implementations.html

**Comment by arthurkiller** [comment]
这个可以加入到计划中,不过现在来看还没有内置类似于 gfw  的功能

**Comment by M2shad0w** [comment]
希望加入该功能

**Comment by thisforeda** [comment]
嗯，希望客户端版本可以配置一个监听本地HTTP PAC请求的项（就像shadowsocks-windows的那个本地PAC功能）。
我现在的情况就是在服务器上开了一个小脚本处理PAC请求。

谢谢！

**Comment by penhauer-xiao** [comment]
1年了，有什么计划进展吗？

**Comment by penhauer-xiao** [comment]
![image](https://user-images.githubusercontent.com/6280121/40265466-68b60968-5b6b-11e8-8e82-1ae920bfe3fc.png)

**Comment by penhauer-xiao** [comment]
![image](https://user-images.githubusercontent.com/6280121/40265476-8515f2f8-5b6b-11e8-84f6-421a61532c08.png)

**Comment by arthurkiller** [comment]
Try cow
