### ISSUE TITLE
Why don't provide ss-local release in recent version ?

### ISSUE THREAD

**Issue by eromoe** [shadowsocks/shadowsocks-go#256]
I usually use gui on windows,  but some time need work in a linux server . Everytime install a python version is complex, so I expect portable ability of go and come here.

But only 1.1.5 has ss-local 
https://github.com/shadowsocks/shadowsocks-go/releases

Does it mean ss-local no need update ?

**Comment by arthurkiller** [comment]
nope,  build it yourself

**Comment by eromoe** [comment]
OK, could you provider a simple guide ?

**Comment by arthurkiller** [comment]
@eromoe  run 
> go build

**Comment by arthurkiller** [comment]
make sure you have install go environment

**Comment by eromoe** [comment]
error when go install / gopm install 

```
E:\shadowsocks-go\cmd\shadowsocks-local>go install
D:\Go\gopath\src\github.com\shadowsocks\shadowsocks-go\shadowsocks\encrypt.go:14:2: cannot find pack
age "golang.org/x/crypto/blowfish" in any of:
        D:\Go\src\golang.org\x\crypto\blowfish (from $GOROOT)
        D:\Go\gopath\src\golang.org\x\crypto\blowfish (from $GOPATH)
D:\Go\gopath\src\github.com\shadowsocks\shadowsocks-go\shadowsocks\encrypt.go:15:2: cannot find pack
age "golang.org/x/crypto/cast5" in any of:
        D:\Go\src\golang.org\x\crypto\cast5 (from $GOROOT)
        D:\Go\gopath\src\golang.org\x\crypto\cast5 (from $GOPATH)
D:\Go\gopath\src\github.com\shadowsocks\shadowsocks-go\shadowsocks\encrypt.go:16:2: cannot find pack
age "golang.org/x/crypto/salsa20/salsa" in any of:
        D:\Go\src\golang.org\x\crypto\salsa20\salsa (from $GOROOT)
        D:\Go\gopath\src\golang.org\x\crypto\salsa20\salsa (from $GOPATH)
```

go version 1.75

**Comment by eromoe** [comment]
Fine, 
`go install / gopm install` just say fails. 

Only  `go get -u github.com/shadowsocks/shadowsocks-go/cmd//shadowsocks-local`  would show network connection error.

I really don't appreciate the way go package distribute .  Can't setup mirrors, so there is no China mirror. Global proxy not work for go,  different setting on win and linux .
Once use a proxy, I'd better to revert it after down, or may got problem someday . And I have to setup ss-local python version first to make proxy work.  That's why I am here asking provide ss-local go release.

**Comment by arthurkiller** [comment]
@eromoe  this repo was blocked, in new version, I have added the vendor to solve this problem

**Comment by arthurkiller** [comment]
check your path @eromoe 
> go get -u github.com/shadowsocks/shadowsocks-go/cmd//shadowsocks-local

>go get -u github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local

**Comment by eromoe** [comment]
Double slash is fine.  At the time of last comment, I have successfully built binary.   I just indicated the network error wouldn't show while using `go install`.
