### ISSUE TITLE
It can't work with XAMPP on Ubuntu 16.04

### ISSUE THREAD

**Issue by Super-Passerby** [shadowsocks/shadowsocks-go#259]
# XAMPP can't start while ss-go already running
root@go:~# /opt/lampp/xampp start
Starting XAMPP for Linux 7.1.11-0...
**XAMPP: Starting Apache...fail.**
XAMPP:  Another web server with SSL is already running.
XAMPP: Starting MySQL...ok.
XAMPP: Starting ProFTPD...fail.
Contents of "/opt/lampp/var/proftpd/start.err":
iZrj9e27gpmune7xdmc903Z proftpd[5923]: warning: unable to determine IP address of 'iZrj9e27gpmune7xdmc903Z'
iZrj9e27gpmune7xdmc903Z proftpd[5923]: error: no valid servers configured
iZrj9e27gpmune7xdmc903Z proftpd[5923]: Fatal: error processing configuration file '/opt/lampp/etc/proftpd.conf'

# ss-go also can't  start while XAMPP already is running

root@go:~# /etc/init.d/shadowsocks start
Starting Shadowsocks-go failed

How to running both of them at the some time?

***Many thanks for your amazing work***

**Comment by thisforeda** [comment]
### port confict, stupid question.
