### ISSUE TITLE
Option to disable logging of client ips

### ISSUE THREAD

**Issue by abeluck** [shadowsocks/shadowsocks-go#265]
Currently, shadowsocks-go will write the client ip address to the log if a connection fails:

```
Feb 05 14:45:49 shadowsocks-test-ansible shadowsocks-server[30172]: 2018/02/05 14:45:49 error getting request client.ip:port 10.0.2.15:443 read tcp 10.0.2.15:443->client.ip:port:43000: read: 
connection reset by peer
```

Ideally there would be an option to disable this for privacy-conscious services who need to keep logs for debugging/perf monitoring but do not want to store client ips.

**Comment by abeluck** [comment]
@arthurkiller  I will create a PR for this. Do you want it submitted against `develop` or `master`? Seems like develop is far behind master.

**Comment by arthurkiller** [comment]
FIXED
