### ISSUE TITLE
Please drop OTA and add AEAD

### ISSUE THREAD

**Issue by JimLee1996** [shadowsocks/shadowsocks-go#267]
- Deprecate OTA (One-Time-Auth).
- Add new ciphers for SIP004: aes-128-gcm, aes-192-gcm, aes-256-gcm, chacha20-poly1305 and chacha20-ietf-poly1305.

[Deprecate stream ciphers with insufficient IV length](https://github.com/shadowsocks/shadowsocks-org/issues/36)

**Comment by arthurkiller** [comment]
@JimLee1996 aead is abandoned?

**Comment by arthurkiller** [comment]
@JimLee1996 there get 2 new designed reconstruction version on this repo, and the release will be soon

**Comment by JimLee1996** [comment]
Gocha! Thank you.

**Comment by larryhu** [comment]
What's time it will be release ?  I can't wait anymore. Thx!

**Comment by arthurkiller** [comment]
testing branch will release before Apr.
