### ISSUE TITLE
用tsocks 连接local server报 socks version not supported  

### ISSUE THREAD

**Issue by wynemo** [shadowsocks/shadowsocks-go#268]
socks 5, python版的没问题

**Comment by arthurkiller** [comment]
Can you show more evidence about this error.
eg. log or screen shortcut

**Comment by wynemo** [comment]
2018/02/24 13:05:27 starting local socks5 server at 0.0.0.0:1080 ...
[DEBUG] 13:05:39 socks connect from 192.168.56.1:49578
2018/02/24 13:05:39 error getting request: socks version not supported


user@xxx:/tmp$ tsocks git clone https://github.com/jdormit/looped-in
Cloning into 'looped-in'...

**Comment by arthurkiller** [comment]
Seems your tsocks did not configure properly. 

> https://sourcegraph.com/github.com/shadowsocks/shadowsocks-go/-/blob/cmd/shadowsocks-local/local.go#L25:2$references

```golang
if buf[idVer] != socksVer5 {
    return errVer
}
```

**Comment by arthurkiller** [comment]
@wynemo  maybe `TSOCKS_DEBUG` `TSOCKS_DEBUG_FILE` can help

https://linux.die.net/man/8/tsocks

**Comment by wynemo** [comment]
looks like it's tsocks' own issue.
