### ISSUE TITLE
与shadowsocks-py兼容性问题

### ISSUE THREAD

**Issue by iceonsun** [shadowsocks/shadowsocks-go#271]
你好，想请问一下，README中指定的兼容是什么意思。
指的是shadowsocks-go的client与server兼容，还是shadowsocks-go与shadowsocks-py完全兼容。
完全兼容指的是：
比如客户端用shadowsocks-py，服务端用shadowsocks-go；或者客户端go，服务端py。这两种情况下都兼容。

**Comment by arthurkiller** [comment]
protocol

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️

Arthur lee

**Comment by iceonsun** [comment]
想再想作者请教个问题，请问测试过shadowsocks-go和shadowsocks-py的速度吗。如果有的话，大概谁快一点，快大约多少？我这里粗略测试了3次，两者速度差距在10%左右。

**Comment by arthurkiller** [comment]
choose what u like

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️

Arthur lee
