### ISSUE TITLE
How to use as websocket  proxy ?

### ISSUE THREAD

**Issue by FajunChen** [shadowsocks/shadowsocks-go#273]
I am using websocket-client, and try to receive socket streaming through shadowsocks proxy, but failed. Can anyone please give some help?

```python
from websocket import create_connection
import socket
ws=create_connection("ws://echo.websocket.org/", http_proxy_host="127.0.0.1", http_proxy_port=1080)
ws.send("hello")
ws.recv()
```

I know that it could be the improper argument "http_proxy_host", however, I can't find any other options more suitable. Do I need to install polipo as a socket/http converter?

**Comment by arthurkiller** [comment]
Not a shadowsocks-go bug, Pls put this issue into right place

CLOSED

**Comment by arthurkiller** [comment]
@FajunChen  Shadowsocks only provide socks5 interface on client side.
may be polipo or Proxyv can help
