### ISSUE TITLE
关于local跟server建立连接的问题

### ISSUE THREAD

**Issue by zhenjunMa** [shadowsocks/shadowsocks-go#274]
hi，这两天看源码有个问题想请教下：

浏览器跟ss-local建立建立的时候源码中按照socks5协议进行了握手处理。
而在ss-local跟ss-server建立连接的时候却没有遵守socks5协议，都是自己写。

疑问：
理论上来说，浏览器跟ss-local，ss-local跟ss-server两者建立连接都应该遵守socks5的握手协议（包括解析协议头），但源码中没有这样做的原因是浏览器使用插件连ss-local，插件是别人写的，因此它们之间通信必须严格遵守socks5协议，而由于ss-local跟ss-server建立连接解析数据都是自己写，因此只要自己制定一种数据格式即可，不必完全遵守socks5协议。

不知道我这么理解对不？ 还是有其他的问题我没考虑到？

谢谢。

**Comment by arthurkiller** [comment]
@zhenjunMa
https://shadowsocks.org/en/spec/Protocol.html

AND DO NOT ASK ABOUT HOW IT WORKS IN ISSUE.

closed
