### ISSUE TITLE
在win10 专业版1709 版本 报socket错误

### ISSUE THREAD

**Issue by chengziqing** [shadowsocks/shadowsocks-go#277]
win10 家庭版都可以，只是在win10 专业版1709 版本 报socket错误。杀毒软件，啥的都没有。

**Comment by chengziqing** [comment]
微软这次1709更新后弃用功能“TLS RC4密码”。照成的ＢＵＧ

**Comment by arthurkiller** [comment]
RC4 is not secure enough.
thx for your report

**Comment by chengziqing** [comment]
2018/03/28 17:25:56 [019] WARN: Error copying to client: readfrom tcp 127.0.0.1:56948->127.0.0.1:49865: read tcp 127.0.0.1:49866->127.0.0.1:56946: wsarecv: An existing connection was forcibly closed by the remote host.
2018/03/28 17:26:01 error connecting to shadowsocks server: dial tcp 208.115.109.131:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by chengziqing** [comment]
跑了一下，把错误日志，发来了

**Comment by chengziqing** [comment]
可能不是这个问题，特意安装了win10 1709 16299.125。这个版本，测试一下，是可以的。我再看看是否是其他版本问题

**Comment by chengziqing** [comment]
不好意思，我测试了，16299.309版本也行，估计不是这个问题。这个可以关闭了
