### ISSUE TITLE
log上显示piping，但还是无法打开网页

### ISSUE THREAD

**Issue by eschao** [shadowsocks/shadowsocks-go#280]
突然shadowsocks不能用了，之前用的python版本，今天尝试下go版本，下载最新的代码，编译server和local端，配置后尝试打开google，只看到连接上了，但一直无法打开显示网页内容，server端日志如下：
>2018/04/24 00:46:10 server listening port 29443 ...
2018/04/24 00:47:09 creating cipher for port: 29443
[DEBUG] 00:47:09 new client 106.38.0.121:15614->98.142.142.55:29443
[DEBUG] 00:47:10 connecting www.google.com:443
[DEBUG] 00:47:10 piping 106.38.0.121:15614<->www.google.com:443 ota=false connOta=false

也不报错，直到client端出现timeout。server是ubuntu 16.04，确认访问google没问题(米国VPS), 用ssh做反向代理，本地就能访问google。不知道是不是我的server系统配置的问题？但没有动过呀！求助下大家，谢谢！

**Comment by arthurkiller** [comment]
pls paste complete log on both server and client.

**Comment by arthurkiller** [comment]
closed

**Comment by eschao** [comment]
@arthurkiller 以下是我访问twitter.com的日志：

* 客户端日志：
2018/05/08 14:11:03 available remote server 98.142.142.55:9443
2018/05/08 14:11:03 starting local socks5 server at :1080 ...
[DEBUG] 14:11:11 socks connect from 127.0.0.1:53571
[DEBUG] 14:11:11 connected to www.google.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:12 socks connect from 127.0.0.1:53574
[DEBUG] 14:11:13 connected to www.google.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:13 socks connect from 127.0.0.1:53577
[DEBUG] 14:11:13 socks connect from 127.0.0.1:53576
[DEBUG] 14:11:13 socks connect from 127.0.0.1:53578
[DEBUG] 14:11:13 socks connect from 127.0.0.1:53583
[DEBUG] 14:11:13 socks connect from 127.0.0.1:53582
[DEBUG] 14:11:13 socks connect from 127.0.0.1:53586
[DEBUG] 14:11:13 connected to www.gstatic.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:13 connected to ssl.gstatic.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:13 connected to apis.google.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:13 socks connect from 127.0.0.1:53588
[DEBUG] 14:11:13 connected to www.google.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:13 connected to www.google.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:13 connected to www.google.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:13 connected to www.google.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:16 socks connect from 127.0.0.1:53590
[DEBUG] 14:11:16 connected to www.twitter.com:443 via 98.142.142.55:9443
[DEBUG] 14:11:42 closed connection to www.google.com:443
[DEBUG] 14:11:43 closed connection to apis.google.com:443
[DEBUG] 14:11:43 closed connection to ssl.gstatic.com:443
[DEBUG] 14:11:43 closed connection to www.google.com:443
[DEBUG] 14:11:43 closed connection to www.google.com:443
[DEBUG] 14:11:43 closed connection to www.google.com:443
[DEBUG] 14:11:43 closed connection to www.google.com:443
[DEBUG] 14:11:46 socks connect from 127.0.0.1:53605
[DEBUG] 14:11:46 closed connection to www.twitter.com:443
[DEBUG] 14:11:46 connected to www.gstatic.com:80 via 98.142.142.55:9443
[DEBUG] 14:11:46 socks connect from 127.0.0.1:53607
[DEBUG] 14:11:46 closed connection to www.gstatic.com:443
[DEBUG] 14:11:46 socks connect from 127.0.0.1:53609
[DEBUG] 14:11:47 connected to api.userstyles.org:443 via 98.142.142.55:9443
[DEBUG] 14:11:47 connected to www.twitter.com:443 via 98.142.142.55:9443
[DEBUG] 14:12:16 closed connection to api.userstyles.org:443
[DEBUG] 14:12:16 closed connection to www.twitter.com:443
[DEBUG] 14:12:21 socks connect from 127.0.0.1:53616
[DEBUG] 14:12:22 connected to www.twitter.com:443 via 98.142.142.55:9443
[DEBUG] 14:12:27 closed connection to www.google.com:443
[DEBUG] 14:12:51 closed connection to www.twitter.com:443

**服务器端日志**
2018/05/08 02:10:59 server listening port 9443 ...
2018/05/08 02:11:11 creating cipher for port: 9443
[DEBUG] 02:11:11 new client 106.38.0.87:53572->98.142.142.55:9443
[DEBUG] 02:11:12 new client 106.38.0.87:13428->98.142.142.55:9443
[DEBUG] 02:11:13 new client 106.38.0.87:53580->98.142.142.55:9443
[DEBUG] 02:11:13 new client 106.38.0.87:53579->98.142.142.55:9443
[DEBUG] 02:11:13 new client 106.38.0.87:64936->98.142.142.55:9443
[DEBUG] 02:11:13 new client 106.38.0.87:3255->98.142.142.55:9443
[DEBUG] 02:11:13 new client 106.38.0.87:39642->98.142.142.55:9443
[DEBUG] 02:11:13 new client 106.38.0.87:37324->98.142.142.55:9443
[DEBUG] 02:11:13 connecting www.google.com:443
[DEBUG] 02:11:13 piping 106.38.0.87:53572<->www.google.com:443 ota=false connOta=false
[DEBUG] 02:11:13 new client 106.38.0.87:60945->98.142.142.55:9443
[DEBUG] 02:11:14 connecting www.google.com:443
[DEBUG] 02:11:14 piping 106.38.0.87:13428<->www.google.com:443 ota=false connOta=false
[DEBUG] 02:11:14 connecting www.gstatic.com:443
[DEBUG] 02:11:14 connecting ssl.gstatic.com:443
[DEBUG] 02:11:14 connecting apis.google.com:443
[DEBUG] 02:11:14 connecting www.google.com:443
[DEBUG] 02:11:14 piping 106.38.0.87:53580<->www.gstatic.com:443 ota=false connOta=false
[DEBUG] 02:11:14 piping 106.38.0.87:53579<->apis.google.com:443 ota=false connOta=false
[DEBUG] 02:11:14 piping 106.38.0.87:3255<->www.google.com:443 ota=false connOta=false
[DEBUG] 02:11:15 piping 106.38.0.87:64936<->ssl.gstatic.com:443 ota=false connOta=false
[DEBUG] 02:11:15 connecting www.google.com:443
[DEBUG] 02:11:15 connecting www.google.com:443
[DEBUG] 02:11:15 piping 106.38.0.87:37324<->www.google.com:443 ota=false connOta=false
[DEBUG] 02:11:15 piping 106.38.0.87:39642<->www.google.com:443 ota=false connOta=false
[DEBUG] 02:11:15 connecting www.google.com:443
[DEBUG] 02:11:15 piping 106.38.0.87:60945<->www.google.com:443 ota=false connOta=false
[DEBUG] 02:11:16 new client 106.38.0.87:30083->98.142.142.55:9443
[DEBUG] 02:11:18 connecting www.twitter.com:443
[DEBUG] 02:11:18 piping 106.38.0.87:30083<->www.twitter.com:443 ota=false connOta=false
[DEBUG] 02:11:23 closed pipe 106.38.0.87:53572<->www.google.com:443
[DEBUG] 02:11:24 closed pipe 106.38.0.87:13428<->www.google.com:443
[DEBUG] 02:11:24 closed pipe 106.38.0.87:53579<->apis.google.com:443
[DEBUG] 02:11:25 closed pipe 106.38.0.87:3255<->www.google.com:443
[DEBUG] 02:11:25 closed pipe 106.38.0.87:64936<->ssl.gstatic.com:443
[DEBUG] 02:11:25 closed pipe 106.38.0.87:39642<->www.google.com:443
[DEBUG] 02:11:25 closed pipe 106.38.0.87:37324<->www.google.com:443
[DEBUG] 02:11:25 closed pipe 106.38.0.87:60945<->www.google.com:443
[DEBUG] 02:11:46 new client 106.38.0.87:61391->98.142.142.55:9443
[DEBUG] 02:11:46 new client 106.38.0.87:5589->98.142.142.55:9443
[DEBUG] 02:11:47 new client 106.38.0.87:16943->98.142.142.55:9443
[DEBUG] 02:11:48 connecting www.gstatic.com:80
[DEBUG] 02:11:48 closed pipe 106.38.0.87:30083<->www.twitter.com:443
[DEBUG] 02:11:48 piping 106.38.0.87:61391<->www.gstatic.com:80 ota=false connOta=false
[DEBUG] 02:11:48 connecting api.userstyles.org:443
[DEBUG] 02:11:48 connecting www.twitter.com:443
[DEBUG] 02:11:48 piping 106.38.0.87:16943<->www.twitter.com:443 ota=false connOta=false
[DEBUG] 02:11:48 piping 106.38.0.87:5589<->api.userstyles.org:443 ota=false connOta=false
[DEBUG] 02:12:18 closed pipe 106.38.0.87:16943<->www.twitter.com:443
[DEBUG] 02:12:22 new client 106.38.0.87:53617->98.142.142.55:9443
[DEBUG] 02:12:23 connecting www.twitter.com:443
[DEBUG] 02:12:23 piping 106.38.0.87:53617<->www.twitter.com:443 ota=false connOta=false
[DEBUG] 02:12:48 closed pipe 106.38.0.87:5589<->api.userstyles.org:443
[DEBUG] 02:12:53 closed pipe 106.38.0.87:53617<->www.twitter.com:443
[DEBUG] 02:13:01 closed pipe 106.38.0.87:53580<->www.gstatic.com:443
[DEBUG] 02:13:22 new client 106.38.0.87:31822->98.142.142.55:9443
[DEBUG] 02:13:23 connecting www.twitter.com:443
[DEBUG] 02:13:23 piping 106.38.0.87:31822<->www.twitter.com:443 ota=false connOta=false
[DEBUG] 02:13:53 closed pipe 106.38.0.87:31822<->www.twitter.com:443
[DEBUG] 02:14:31 closed pipe 106.38.0.87:61391<->www.gstatic.com:80
[DEBUG] 02:14:32 new client 106.38.0.87:44972->98.142.142.55:9443
[DEBUG] 02:14:33 connecting www.gstatic.com:80
[DEBUG] 02:14:33 piping 106.38.0.87:44972<->www.gstatic.com:80 ota=false connOta=false

请帮忙分析下，多谢

**Comment by eschao** [comment]
@arthurkiller chrome browser一直转，什么也不显示，就是loading半天，最后停了，跟打不开网页一样。用firefox的话，状态栏显示Performing TLS....之类的，server那边我是ubuntu 14.04， 客服端这边是用的macOS最新版，我也比较奇怪，突然shadow就不好用了，Ubuntu我也update了，但还是不起作用。

**Comment by arthurkiller** [comment]
have you try to restart the ss-server?

**Comment by arthurkiller** [comment]
make sure you config(username, passwd, encryptor method) is correct on both server and client

**Comment by eschao** [comment]
@arthurkiller 现在我可以，先试ios，确保server端没问题，然后升级了下macos，重启后用go版的cmd可以，其他那些GUI的client不行，我再试试我本行不行。看来多半是macos的问题，mac一升级，估计有些lib变了，或者有bug。
Anyway，thanks

**Comment by arthurkiller** [comment]
np.

And you are free to reopen this issue anytime.
