### ISSUE TITLE
shadowsocks-go支持的 AEAD 算法ChaCha20-IETF-Poly1305 了吗

### ISSUE THREAD

**Issue by lsnmx** [shadowsocks/shadowsocks-go#281]
如题谢谢

**Comment by arthurkiller** [comment]
WIP in fork branch.

**Comment by lsnmx** [comment]
@arthurkiller  不会编译你这个啊，只会 go get -u github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server

**Comment by lsnmx** [comment]
@arthurkiller  谢谢，请更新下到github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server吧
