### ISSUE TITLE
building shadowsocks-go into a bundle of pluggable transports

### ISSUE THREAD

**Issue by eighthave** [shadowsocks/shadowsocks-go#282]
We're making a lib to make using pluggable transports like this one really easy to use for Android devs.  This involves building multiple projects into a single JNI _.so_library, then selectively calling a method to start the specific transport.  That requires that each transport's code does not have an exported `main()` function.  I suck at Go, so I'm open to suggestions.  So I'm opening this issue to figure out how to make shadowsocks-go integratable.

Here's the project for the piece that the Android dev interfaces with:
https://github.com/guardianproject/AndroidPluggableTransportsDispatcher

Here's the project where we build all of the various Go pluggable transports into the JNI bundle used by AndroidPluggableTransportsDispatcher:
 https://gitlab.com/eighthave/goptbundle

@n8fr8

**Comment by eighthave** [comment]
thanks!  the new version you mention is something that already exists,
or something that you are still working on?

**Comment by arthurkiller** [comment]
still work in progress
