### ISSUE TITLE
Repetitive message error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused

### ISSUE THREAD

**Issue by hanxue** [shadowsocks/shadowsocks-go#287]
I am running a DigitalOcean droplet (VM) with a pre-assigned IP address (e.g. 1.1.1.1). I have also assigned a Floating IP address (e.g. 2.2.2.2). Connecting to shadowsocks-go using 1.1.1.1 works fine. But if I connect using 2.2.2.2, I get this error

```
2018/05/11 06:48:37 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:37 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:38 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:38 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:39 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:39 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:40 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:40 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:41 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
2018/05/11 06:48:42 error connecting to: localhost:9229 dial tcp 127.0.0.1:9229: connect: connection refused
```

Is there anything else I need to configure to use Floating IPs?

**Comment by arthurkiller** [comment]
You need to confirm what is your WAN ip address outside the service provider.

**Comment by hanxue** [comment]
@arthurkiller I have verified that both IP address is pingable, and I can SSH to the server using both the static IPv4 address, and the assigned Floating IP. 

Just that shadowsocks-go keep giving the error message above

**Comment by arthurkiller** [comment]
make sure your firewall has accept the port `9229`

**Comment by arthurkiller** [comment]
Are you sure? I can't see.

Anyway, you can try to test yourself. shut down your shadowsocks server and do this:
```
sudo nc -l 9229
```
do this on any where

```
nc xxx 9229 -v
```

And you can check.

**Comment by arthurkiller** [comment]
Closed, and you are free to reopen.

**Comment by hanxue** [comment]
The line 

```
8080:9999/tcp              ALLOW IN    Anywhere 
8080:9999/tcp              ALLOW IN    Anywhere (v6)
```

should already include the port 9229. 


Just to be sure, I specifically add a rule for port `9229` for IPv4 and IPv6

This is how my UFW rules look like now

```
To                         Action      From
--                         ------      ----
22                         ALLOW IN    Anywhere
80/tcp                     ALLOW IN    Anywhere 
1194/udp                   ALLOW IN    Anywhere 
443                        ALLOW IN    Anywhere 
8000                       ALLOW IN    Anywhere 
8080:9999/tcp              ALLOW IN    Anywhere 
60000:61000/udp            ALLOW IN    Anywhere 
9229                       ALLOW IN    Anywhere 
80/tcp                     ALLOW IN    Anywhere (v6)
443                        ALLOW IN    Anywhere (v6)
8000                       ALLOW IN    Anywhere (v6)
22                         ALLOW IN    Anywhere (v6)
8080:9999/tcp              ALLOW IN    Anywhere (v6)
60000:61000/udp            ALLOW IN    Anywhere (v6)
9229                       ALLOW IN    Anywhere (v6)
```
On server

```
$ sudo nc -l 9229
[hangs]
```

On client

```
$ nc 1.1.1.1 9229 -v
1.1.1.1 9229: Connection refused
$ nc 2.2.2.2 9229 -v
2.2.2.2 9229: Connection refused
```

`1.1.1.1` replaced with actual IPv4 address and `2.2.2.2` replaced with Floating IP address of course.

**Comment by arthurkiller** [comment]
This is not the bug of shadowsocks. Pls contact your service provider and ask for more help.

**Comment by arthurkiller** [comment]
By the way. Cloud virtual machine has it own way to route the request, most of them use SDN to provide network connection for container. 

You should do this on the web console but not the host.

**Comment by hanxue** [comment]
@arthurkiller  No, this has to do with shadowsocks itself. The floating IP 2.2.2.2 is simply an alias of 1.1.1.1. On the server itself, `ifconfig` will always return `1.1.1.1`. But any connection from outside the data center to 2.2.2.2 will be routed to 1.1.1.1

This is the traceroute to 1.1.1.1

![image](https://user-images.githubusercontent.com/760008/40038840-ad15aa6e-5846-11e8-9d45-a084835909ba.png)



This is the traceroute to 2.2.2.2

![image](https://user-images.githubusercontent.com/760008/40038764-6582058a-5846-11e8-9f5f-3280c910a7fc.png)


As you can see, the traceroute results works for both IP addresses. 

The error message above occurs because shadowsocks-go cannot resolve the IP address for 2.2.2.2. 

I don't want to use 1.1.1.1 because when the server gets shut down, or I replace it with another VM, then the IP changes. But 2.2.2.2 will always be assigned for the shadowsocks service. 

Is there any workaround for that?

**Comment by arthurkiller** [comment]
Nothing.

**Comment by arthurkiller** [comment]
There is no evidence that this is a common issue.
