### ISSUE TITLE
socks handshake: socks version not supported

### ISSUE THREAD

**Issue by aqing1987** [shadowsocks/shadowsocks-go#289]
Hi, 
I build a shadowsocks-local in window7, when I run I got the following issue:

```
2018/05/24 23:22:46 socks ver: 71
2018/05/24 23:22:46 socks handshake: socks version not supported
2018/05/24 23:22:46 socks ver: 71
2018/05/24 23:22:46 socks handshake: socks version not supported
2018/05/24 23:23:06 socks ver: 71
2018/05/24 23:23:06 socks handshake: socks version not supported
2018/05/24 23:23:06 socks ver: 71
```
the 71 is my log, as below:
```
        if buf[idVer] != socksVer5 {		
		log.Println("socks ver:", buf[idVer])
		return errVer
	}
```

Version Info:
PS D:\GOPHOME\bin> .\shadowsocks-local.exe --version
shadowsocks-go version 1.2.0

Any help ? 

Thanks

**Comment by arthurkiller** [comment]
you should use socks5 client

**Comment by ednew2018** [comment]
windows dose not have native support of Socks5, so we need convert it to https proxy using privoxy
