### ISSUE TITLE
error getting request <...> addr type <xx> not supported

### ISSUE THREAD

**Issue by nodje** [shadowsocks/shadowsocks-go#29]
I can establish a connection between server and local, but I can't get traffic go through:

server side:
`shadowsocks-server -d > log &
tail -f log
2014/03/13 19:25:54 server listening port 8388 ...
2014/03/13 19:26:18 creating cipher for port: 8388
[DEBUG] 19:26:18 new client <client_ip>:13011-><server_ip>:8388
2014/03/13 19:26:18 error getting request <client_ip>:13011 <server_ip>:8388 addr type 94 not supported
[DEBUG] 19:26:18 closed pipe <client_ip>:13011<->
[DEBUG] 19:26:19 new client <client_ip>:13036-><server_ip>:8388
2014/03/13 19:26:19 error getting request <client_ip>:13036 <server_ip>:8388 addr type 156 not supported
[DEBUG] 19:26:19 closed pipe <client_ip>:13036<->
[DEBUG] 19:26:19 new client <client_ip>:13045-><server_ip>:8388
2014/03/13 19:26:19 error getting request <client_ip>:13045 <server_ip>:8388 addr type 10 not supported
[DEBUG] 19:26:19 closed pipe <client_ip>:13045<->
[DEBUG] 19:26:20 new client <client_ip>:13085-><server_ip>:8388
2014/03/13 19:26:20 error getting request <client_ip>:13085 <server_ip>:8388 addr type 14 not supported
[DEBUG] 19:26:20 closed pipe <client_ip>:13085<->
[DEBUG] 19:27:06 new client <client_ip>:14970-><server_ip>:8388
2014/03/13 19:27:06 error getting request <client_ip>:14970 <server_ip>:8388 addr type 36 not supported
[DEBUG] 19:27:06 closed pipe <client_ip>:14970<->
[DEBUG] 19:27:06 new client <client_ip>:14973-><server_ip>:8388
2014/03/13 19:27:06 error getting request <client_ip>:14973 <server_ip>:8388 addr type 64 not supported
[DEBUG] 19:27:06 closed pipe <client_ip>:14973<->
[DEBUG] 19:27:06 new client <client_ip>:14986-><server_ip>:8388
2014/03/13 19:27:06 error getting request <client_ip>:14986 <server_ip>:8388 addr type 119 not supported
[DEBUG] 19:27:06 closed pipe <client_ip>:14986<->
[DEBUG] 19:27:06 new client <client_ip>:14987-><server_ip>:8388
2014/03/13 19:27:06 error getting request <client_ip>:14987 <server_ip>:8388 addr type 249 not supported
[DEBUG] 19:27:06 closed pipe <client_ip>:14987<->
[DEBUG] 19:27:06 new client <client_ip>:14989-><server_ip>:8388
2014/03/13 19:27:06 error getting request <client_ip>:14989 <server_ip>:8388 addr type 30 not supported
[DEBUG] 19:27:06 closed pipe <client_ip>:14989<->
[DEBUG] 19:27:06 new client <client_ip>:14990-><server_ip>:8388
2014/03/13 19:27:06 error getting request <client_ip>:14990 <server_ip>:8388 addr type 154 not supported
[DEBUG] 19:27:06 closed pipe <client_ip>:14990<->
[DEBUG] 19:27:07 new client <client_ip>:14996-><server_ip>:8388
2014/03/13 19:27:07 error getting request <client_ip>:14996 <server_ip>:8388 addr type 42 not supported
[DEBUG] 19:27:07 closed pipe <client_ip>:14996<->
[DEBUG] 19:27:07 new client <client_ip>:14998-><server_ip>:8388
2014/03/13 19:27:07 error getting request <client_ip>:14998 <server_ip>:8388 addr type 70 not supported
[DEBUG] 19:27:07 closed pipe <client_ip>:14998<->
[DEBUG] 19:27:07 new client <client_ip>:15000-><server_ip>:8388
2014/03/13 19:27:07 error getting request <client_ip>:15000 <server_ip>:8388 addr type 56 not supported
[DEBUG] 19:27:07 closed pipe <client_ip>:15000<->
[DEBUG] 19:27:07 new client <client_ip>:15009-><server_ip>:8388
2014/03/13 19:27:07 error getting request <client_ip>:15009 <server_ip>:8388 addr type 136 not supported
[DEBUG] 19:27:07 closed pipe <client_ip>:15009<->
[DEBUG] 19:27:07 new client <client_ip>:15021-><server_ip>:8388
2014/03/13 19:27:07 error getting request <client_ip>:15021 <server_ip>:8388 addr type 17 not supported
[DEBUG] 19:27:07 closed pipe <client_ip>:15021<->
[DEBUG] 19:27:08 new client <client_ip>:15035-><server_ip>:8388
2014/03/13 19:27:08 error getting request <client_ip>:15035 <server_ip>:8388 addr type 84 not supported
[DEBUG] 19:27:08 closed pipe <client_ip>:15035<->`

Client side:
`shadowsocks-local -d -c .shadowsock
2014/03/13 19:26:12 available remote server <server_ip>:8388
2014/03/13 19:26:12 starting local socks5 server at :2000 ...
[DEBUG] 19:26:17 socks connect from 127.0.0.1:56990
[DEBUG] 19:26:18 connected to www.google.com:80 via <server_ip>:8388
[DEBUG] 19:26:18 closed connection to www.google.com:80
[DEBUG] 19:26:18 socks connect from 127.0.0.1:56992
[DEBUG] 19:26:18 connected to www.qwant.com:443 via <server_ip>:8388
[DEBUG] 19:26:19 closed connection to www.qwant.com:443
[DEBUG] 19:26:19 socks connect from 127.0.0.1:56994
[DEBUG] 19:26:19 connected to www.qwant.com:443 via <server_ip>:8388
[DEBUG] 19:26:19 closed connection to www.qwant.com:443
[DEBUG] 19:26:19 socks connect from 127.0.0.1:56996
[DEBUG] 19:26:20 connected to www.qwant.com:443 via <server_ip>:8388
[DEBUG] 19:26:20 closed connection to www.qwant.com:443
[DEBUG] 19:27:05 socks connect from 127.0.0.1:57000
[DEBUG] 19:27:05 socks connect from 127.0.0.1:57002
[DEBUG] 19:27:06 socks connect from 127.0.0.1:57004
[DEBUG] 19:27:06 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:06 closed connection to clients1.google.com:443
[DEBUG] 19:27:06 socks connect from 127.0.0.1:57006
[DEBUG] 19:27:06 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:06 closed connection to clients1.google.com:443
[DEBUG] 19:27:06 socks connect from 127.0.0.1:57008
[DEBUG] 19:27:06 socks connect from 127.0.0.1:57010
[DEBUG] 19:27:06 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:06 closed connection to clients1.google.com:443
[DEBUG] 19:27:06 connected to www.ipchicken.com:80 via <server_ip>:8388
[DEBUG] 19:27:06 socks connect from 127.0.0.1:57012
[DEBUG] 19:27:06 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:06 closed connection to clients1.google.com:443
[DEBUG] 19:27:06 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:06 closed connection to clients1.google.com:443
[DEBUG] 19:27:06 socks connect from 127.0.0.1:57014
[DEBUG] 19:27:06 closed connection to www.ipchicken.com:80
[DEBUG] 19:27:06 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:06 closed connection to clients1.google.com:443
[DEBUG] 19:27:06 socks connect from 127.0.0.1:57016
[DEBUG] 19:27:06 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:06 closed connection to clients1.google.com:443
[DEBUG] 19:27:07 socks connect from 127.0.0.1:57018
[DEBUG] 19:27:07 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:07 connected to www.google.com:80 via <server_ip>:8388
[DEBUG] 19:27:07 closed connection to clients1.google.com:443
[DEBUG] 19:27:07 socks connect from 127.0.0.1:57020
[DEBUG] 19:27:07 closed connection to www.google.com:80
[DEBUG] 19:27:07 connected to clients1.google.com:443 via <server_ip>:8388
[DEBUG] 19:27:07 closed connection to clients1.google.com:443
[DEBUG] 19:27:07 socks connect from 127.0.0.1:57022
[DEBUG] 19:27:08 connected to www.google.com:80 via <server_ip>:8388
[DEBUG] 19:27:08 closed connection to www.google.com:80`

**Comment by JonasGroeger** [comment]
Also check the cipher!

**Comment by hanhuizhu** [comment]
你好，我在使用流量热点的情况下，PC可以顺利翻墙。但是我的PC切成WIFI后，就无法正常翻墙，之前WIFI环境下可以正常相应。请问这可能是什么问题造成的？还提供资讯服务吗？ @cyfdecyf

**Comment by hanhuizhu** [comment]
补充一下，我的服务器是可以正常访问的，有10%左右的丢包 @cyfdecyf
