### ISSUE TITLE
Limiting tunneled connections from server, in a multiuser context

### ISSUE THREAD

**Issue by florian-gh** [shadowsocks/shadowsocks-go#290]
I'm planning to set up a server for several users, and I would like to be able to restrict the outgoing IP addresses where each user can connect. This would be a new feature, and I was thinking on how to implement it.
I'm thinking of a configuration syntax like the following:
```
{
	// we're on a single port, not multi-port configuration
	"password_config": [
		{ "password": "barfoo", "allow": [ "192.168.0.1:80" ] },
		{ "password": "foobar", ... }
	},
	...
}
```
which, given the password that was used for a connection, only allows tunnels that match with "allow" list. The specification of the restrictions can then be enhanced to allow wildcards, regexps, blacklists ("deny") and more, the logic would be the same.
Does this seem reasonable and easy to implement? If yes, I'll see if I can work on such a feature.

**Comment by arthurkiller** [comment]
Most requests access to internet via NAT. The outter ip:port is hard to clearify.

And most of ss-server works on virtual server with firewall.
