### ISSUE TITLE
关于“流量”一词的变量名与函数名问题

### ISSUE THREAD

**Issue by dylanchu** [shadowsocks/shadowsocks-go#292]
嗨各位，我注意到程序中关于“流量”一词的翻译皆是"flow"，虽然不是个大问题，但“flow”一般可看做某次会话及这次会话所涉及的元数据的概括，而“traffic”则更侧重于表示若干会话的数据统计结果，更接近于要表述的“使用量的统计”这个意思，所以从规范的角度考虑翻译为"traffic"是不是更恰当一些？

**Comment by arthurkiller** [comment]
thx for your contribute, and you are free to reopen this issue
