### ISSUE TITLE
OpenVZ VPS上内存占用过多

### ISSUE THREAD

**Issue by yanunon** [shadowsocks/shadowsocks-go#3]
在内存为128M、系统为64bit Debian6的OpenVZ VPS上只能保持25个左右的连接，每个连接使用了3个goroutine，算下来每个goroutine占用了1MB+的内存。

连接大于25个时，不能开辟新的内存空间，程序崩溃。

**Comment by ddatsh** [comment]
咨询下现在官方的binary是怎么编译出来的呀

**Comment by lixin9311** [comment]
https://github.com/shadowsocks/shadowsocks-go/issues/3
