### ISSUE TITLE
正式版本？?????????????????????

### ISSUE THREAD

**Issue by lsnmx** [shadowsocks/shadowsocks-go#305]
正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????正式版本？?????????????????????

**Comment by arthurkiller** [comment]
https://github.com/shadowsocks/shadowsocks-go/releases
