### ISSUE TITLE
Password bug

### ISSUE THREAD

**Issue by kxmp** [shadowsocks/shadowsocks-go#34]
It's on windows client.
When password include %
cli client can't pass authentication,other client not have that problem.

**Comment by genzj** [comment]
`%` is the variable dereference prefix in windows cmdline. instead of passing `%` directly to application, an additional `^` should be added before each literal `%`. For example

```
D:\>set PASS=1

D:\>echo a%PASS%word
a1word

D:\>echo a^%PASS^%word
a%PASS%word
```

**Comment by lixin9311** [comment]
Closed as @genzj have answered the question.
