### ISSUE TITLE
managerAddr var in server.go? 

### ISSUE THREAD

**Issue by fan123199** [shadowsocks/shadowsocks-go#415]
`flag.StringVar(&managerAddr, "manager-address", "", "shadowsocks manager listening address")`

In `server.go` , there is code about managerAddr, but it is not mentioned in README.md. Is it a function of managing multi-user? Is it available in current version?

**Comment by arthurkiller** [comment]
Yes, I thing the PullRequest contributor has forgot the README.md.

I will add later.
