### ISSUE TITLE
status report blocked by channel

### ISSUE THREAD

**Issue by houstar** [shadowsocks/shadowsocks-go#417]
FILE cmd/shadowsocks-server/server.go

LINE 510 declared channel with buffer 1
LINE 518 read from the channel but the channel without any data, so its blocked the status report

**Comment by arthurkiller** [comment]
https://tour.golang.org/concurrency/6

**Comment by houstar** [comment]
YES.  So you can use 'select' to instead of 'switch' :-)

**Comment by arthurkiller** [comment]
closed and  you are free to reopen this issue.

**Comment by houstar** [comment]
**Testcase**

Step 1.  Run the daemon
```
shadowsocks-server --manager-address 127.0.0.1:6001 -d
```
Step 2. Run the testcase
```
import socket

address = ('127.0.0.1', 6001)
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

msg = 'ping'
s.sendto(msg, address)
msg = 'add: {"server_port": 5001, "password":"43347510"}'
s.sendto(msg, address)

while True:
        data=s.recvfrom(1024)
        print data


s.close()
```
**Results after 5 minutes**
```
$ python pytest.py
('pong', ('127.0.0.1', 6001))
('ok', ('127.0.0.1', 6001))

```

there is any response per 10 seconds from the daemon  , could you take a look ?

**Comment by arthurkiller** [comment]
> YES. So you can use 'select' to instead of 'switch' :-)

Oh , that's it.

**Comment by arthurkiller** [comment]
@houstar Thanks for your contribute, dude.
