### ISSUE TITLE
reopen status report issue #417

### ISSUE THREAD

**Issue by houstar** [shadowsocks/shadowsocks-go#418]
This issue #417 blocked the shadowsocks-manager traffic statistic since the shadowsocks-go will not report its traffic status in every 10 seconds.

And I attached the test case to let you verify.

Could you take a look ?

**Comment by arthurkiller** [comment]
Thanks for your contribute. 

Switch should be change into select.

**Comment by arthurkiller** [comment]
fixed in 323704e. Thx again.
