### ISSUE TITLE
package golang.org/x/sys/cpu: unrecognized import path "golang.org/x/sys/cpu" (https fetch: Get https://golang.org/x/sys/cpu?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

### ISSUE THREAD

**Issue by ahkimkoo** [shadowsocks/shadowsocks-go#421]
package golang.org/x/sys/cpu: unrecognized import path "golang.org/x/sys/cpu" (https fetch: Get https://golang.org/x/sys/cpu?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by arthurkiller** [comment]
`go get -u ` after you bypass the GFW

**Comment by kimw** [comment]
golang.org 已被牆。安裝該域名下的 go 包需要架椅作業。
