### ISSUE TITLE
我的ISP可以看到我访问哪个URL地址的网站，当我使用SS？

### ISSUE THREAD

**Issue by jun-dev** [shadowsocks/shadowsocks-go#441]
![screenshot_1](https://user-images.githubusercontent.com/10915074/46801196-29796980-cd84-11e8-8dad-5068644a317a.png)

**Comment by arthurkiller** [comment]
No

**Comment by jun-dev** [comment]
> No
Thank u。 我正在使用fork SSR。 如果我需要使用常规的FTP，我的服务器地址，登录名和密码将被跟踪或不？

**Comment by arthurkiller** [comment]
Ask ssr for more information
