### ISSUE TITLE
我正在使用fork SSR。 如果我需要使用常规的FTP，我的服务器地址，登录名和密码将被跟踪或不？

### ISSUE THREAD

**Issue by jun-dev** [shadowsocks/shadowsocks-go#442]
![screenshot_1](https://user-images.githubusercontent.com/10915074/46802195-dce35d80-cd86-11e8-9581-700db642a276.png)
![screenshot_2](https://user-images.githubusercontent.com/10915074/46802273-11efb000-cd87-11e8-8685-f2e0b0dc7072.png)

**Comment by jun-dev** [comment]
烧焦，非常。
![screenshot_3](https://user-images.githubusercontent.com/10915074/46802763-8545f180-cd88-11e8-898b-1b3b47f5a567.png)

**Comment by arthurkiller** [comment]
Ask ssr for more information
