### ISSUE TITLE
怎么使用windows下shadowsocks Client的CLI

### ISSUE THREAD

**Issue by WyattHuang1** [shadowsocks/shadowsocks-go#445]
Shadowsocks windows版的Client有 CLI 版本吗 ？ 如果有，怎么用？
谢谢！

**Comment by arthurkiller** [comment]
Ask ss c# for more info

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
