### ISSUE TITLE
请问后续是否会增加其它加密方式？

### ISSUE THREAD

**Issue by babyfiv5** [shadowsocks/shadowsocks-go#446]
目前其它语言已经支持chacha20等新型的加密方式，我比较好奇的是为什么不加入Blowfish加密，查到的资料都是说Blowfish比AES的速度要快，安全性又好

**Comment by arthurkiller** [comment]
SS is open source project. Every one can contribute to this repo by put up an pull request.

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by LsnmxNB** [comment]
@babyfiv5  别指望现 shadowsocks-go 的扛摆死（BOSS）了，期望有大神接手才是王道
