### ISSUE TITLE
shadowsocks-local can't curl google,but shadowsocks-qt can

### ISSUE THREAD

**Issue by northfun** [shadowsocks/shadowsocks-go#448]
- Shadowsocks-go-server runs on my server(67.218.130.*).
- My local computer works under a company intranet.
- Both local and remote systems are ubuntu.

I downloaded a Shadowsocks-Qt5(v2.9.0) from ubuntu market,and set the env:`http_proxy=http://127.0.0.1:1080` which is the laddress of Shadowsocks-Qt5,it works well on my terminal.

When I try to using shadowsocks-go-local with a same config file on my terminal, and set the env:`http_proxy="socks5://127.0.0.1:1081"` which is the laddress of shadowsocks-go-local(it seems that `socks5` is the only protocol I can use,when I set to `http`,server would report an err log like `version not support`),then, I can't curl `google` but can curl `baidu`,although both of the commands are sendded to remote server.

Here's some logs from server when I do `curl www.google` by different clients,hope can help me to explain my question.

using shadowsocks-Qt5,and set env:`http_proxy=http://127.0.0.1:1080`,log on server:
```
[DEBUG] 01:40:34 new client 116.246.24.6:48890->67.218.130.198:8389
[DEBUG] 01:40:34 connecting 174.36.228.136:80
```
using shadowsocks-go-local,and set env:`http_proxy="socks5://127.0.0.1:1081"`,log on server:
```
[DEBUG] 01:41:27 new client 116.246.24.6:48944->67.218.130.198:8389
[DEBUG] 01:41:27 connecting www.google.com:80                      
[DEBUG] 01:41:27 piping 116.246.24.6:48944<->www.google.com:80
```
The only different I find on config between qt-client and go-local is that go-local lacks of param `httpProxy` which I set true on qt-client.
I wonder why it happens.

**Comment by arthurkiller** [comment]
ss only provide socks5 interface.

> http://shadowsocks.org/en/spec/Protocol.html

**Comment by arthurkiller** [comment]
I’m not sure weather ss-qt provided http proxy itself. But shadow socks-local did not.

Maybe you can use http proxy with socks5 upstream like privacy or polio.

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
Privoxy Polipo 

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by northfun** [comment]
> I’m not sure weather ss-qt provided http proxy itself. But shadow socks-local did not. Maybe you can use http proxy with socks5 upstream like privacy or polio. Have an awesome day   Arthur lee Sent from my iPhone
> […](#)
> On Nov 6, 2018, at 3:48 PM, NorthFun ***@***.***> wrote: Shadowsocks-go-server runs on my server(67.218.130.*). My local computer works under a company intranet. Both local and remote systems are ubuntu. I downloaded a Shadowsocks-Qt5(v2.9.0) from ubuntu market,and set the env:http_proxy=http://127.0.0.1:1080 which is the laddress of Shadowsocks-Qt5,it works well on my terminal. When I try to using shadowsocks-go-local with a same config file on my terminal, and set the env:http_proxy="socks5://127.0.0.1:1081" which is the laddress of shadowsocks-go-local(it seems that socks5 is the only protocol I can use,when I set to http,server would report an err log like version not support),then, I can't curl google but can curl baidu,although both of the commands are sendded to remote server. Here's some logs from server when I do curl [www.google](http://www.google) by different clients,hope can help me to explain my question. using shadowsocks-Qt5,and set env:http_proxy=http://127.0.0.1:1080,log on server: [DEBUG] 01:40:34 new client 116.246.24.6:48890->67.218.130.198:8389 [DEBUG] 01:40:34 connecting 174.36.228.136:80 using shadowsocks-go-local,and set env:http_proxy="socks5://127.0.0.1:1081",log on server: [DEBUG] 01:41:27 new client 116.246.24.6:48944->67.218.130.198:8389 [DEBUG] 01:41:27 connecting [www.google.com:80](http://www.google.com:80) [DEBUG] 01:41:27 piping 116.246.24.6:48944<->[www.google.com:80](http://www.google.com:80) The only different I find on config between qt-client and go-local is that go-local lacks of param httpProxy which I set true on qt-client. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Could you please explain what cause the different results?

**Comment by northfun** [comment]
> I’m not sure weather ss-qt provided http proxy itself. But shadow socks-local did not. Maybe you can use http proxy with socks5 upstream like privacy or polio. Have an awesome day   Arthur lee Sent from my iPhone
> […](#)
> On Nov 6, 2018, at 3:48 PM, NorthFun ***@***.***> wrote: Shadowsocks-go-server runs on my server(67.218.130.*). My local computer works under a company intranet. Both local and remote systems are ubuntu. I downloaded a Shadowsocks-Qt5(v2.9.0) from ubuntu market,and set the env:http_proxy=http://127.0.0.1:1080 which is the laddress of Shadowsocks-Qt5,it works well on my terminal. When I try to using shadowsocks-go-local with a same config file on my terminal, and set the env:http_proxy="socks5://127.0.0.1:1081" which is the laddress of shadowsocks-go-local(it seems that socks5 is the only protocol I can use,when I set to http,server would report an err log like version not support),then, I can't curl google but can curl baidu,although both of the commands are sendded to remote server. Here's some logs from server when I do curl [www.google](http://www.google) by different clients,hope can help me to explain my question. using shadowsocks-Qt5,and set env:http_proxy=http://127.0.0.1:1080,log on server: [DEBUG] 01:40:34 new client 116.246.24.6:48890->67.218.130.198:8389 [DEBUG] 01:40:34 connecting 174.36.228.136:80 using shadowsocks-go-local,and set env:http_proxy="socks5://127.0.0.1:1081",log on server: [DEBUG] 01:41:27 new client 116.246.24.6:48944->67.218.130.198:8389 [DEBUG] 01:41:27 connecting [www.google.com:80](http://www.google.com:80) [DEBUG] 01:41:27 piping 116.246.24.6:48944<->[www.google.com:80](http://www.google.com:80) The only different I find on config between qt-client and go-local is that go-local lacks of param httpProxy which I set true on qt-client. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Could you please explain what cause the different results?

**Comment by arthurkiller** [comment]
ss standard protocol only required client provide socks5 interface

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
