### ISSUE TITLE
fatal error: MSpanList_Insert

### ISSUE THREAD

**Issue by mrYuandq** [shadowsocks/shadowsocks-go#449]
Mac 上运行 local 出现这样的错误。

failed MSpanList_Insert 0x39a000 0xa8e7c5e5abbf 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x238d60, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff4d0 sp=0x7ffeefbff4b8
runtime.(*mSpanList).insert(0x32bf28, 0x39a000)
	/usr/local/go/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbff500 sp=0x7ffeefbff4d0
runtime.(*mheap).freeSpanLocked(0x32b720, 0x39a000, 0x100, 0x0)
	/usr/local/go/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff568 sp=0x7ffeefbff500
runtime.(*mheap).grow(0x32b720, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff5c0 sp=0x7ffeefbff568
runtime.(*mheap).allocSpanLocked(0x32b720, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff618 sp=0x7ffeefbff5c0
runtime.(*mheap).alloc_m(0x32b720, 0x1, 0x15, 0x0)
	/usr/local/go/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff648 sp=0x7ffeefbff618
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff678 sp=0x7ffeefbff648
runtime.systemstack(0x7ffeefbff698)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff680 sp=0x7ffeefbff678
runtime.(*mheap).alloc(0x32b720, 0x1, 0x10000000015, 0x1454f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff6c8 sp=0x7ffeefbff680
runtime.(*mcentral).grow(0x32d320, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff730 sp=0x7ffeefbff6c8
runtime.(*mcentral).cacheSpan(0x32d320, 0x3277f8)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff770 sp=0x7ffeefbff730
runtime.(*mcache).refill(0x396000, 0x15, 0x7ffeefbff7d8)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff7a8 sp=0x7ffeefbff770
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff7c8 sp=0x7ffeefbff7a8
runtime.systemstack(0x7ffeefbff868)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff7d0 sp=0x7ffeefbff7c8
runtime.mallocgc(0x180, 0x20f240, 0x0, 0x800000000)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbff8a8 sp=0x7ffeefbff7d0
runtime.newobject(0x20f240, 0x327bd0)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbff8d0 sp=0x7ffeefbff8a8
runtime.malg(0x8000, 0x327e40)
	/usr/local/go/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbff908 sp=0x7ffeefbff8d0
runtime.mpreinit(0x328180)
	/usr/local/go/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbff920 sp=0x7ffeefbff908
runtime.mcommoninit(0x328180)
	/usr/local/go/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbff968 sp=0x7ffeefbff920
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbff9b0 sp=0x7ffeefbff968
runtime.rt0_go(0x7ffeefbff9e8, 0x3, 0x7ffeefbff9e8, 0x0, 0x0, 0x3, 0x7ffeefbffb28, 0x7ffeefbffb36, 0x7ffeefbffb39, 0x0, ...)
	/usr/local/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbff9b8 sp=0x7ffeefbff9b0

**Comment by 40780083** [comment]
macOs high Sierra: 10.13.6

**Comment by arthurkiller** [comment]
not sure what happend

try to update go compiler

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by CaiJinKen** [comment]
same error +1, golang is not installed yet, i just execute the client binarry file like this: shadowsocks-local-mac64-1.1.5 --help

**Comment by CaiJinKen** [comment]
I think this error caused by old version of golang, install last golang and rebuild shadowsocks from source. see https://github.com/golang/go/issues/20888
