### ISSUE TITLE
请问怎么限制SS只能访问53 80 443 20 21 22 等常用端口？并限制访问127.0.0.1 、192.168 等IP段？

### ISSUE THREAD

**Issue by GameXG** [shadowsocks/shadowsocks-go#46]
如题，限制后安全性好些。
现在可以用 ss 访问 127.0.0.1 ...

**Comment by lijinpei** [comment]
python和libev版本的相似问题：
https://github.com/shadowsocks/shadowsocks/issues/117
https://github.com/shadowsocks/shadowsocks/issues/176
https://github.com/shadowsocks/shadowsocks-libev/issues/614
https://github.com/shadowsocks/shadowsocks-libev/issues/717
按照clowwindy和madeye的说法用iptables解决。
不过可不可以把ss-server放到docker里呢，假如你愿意在vps上装一个docker。

**Comment by lixin9311** [comment]
关于安全性问题，是在部署的时候考虑的，通过外部手段实现。
例如在一些ssh仅听localhost的情况下，可以通过ss做转发来实现更安全的ssh。
这个功能大概不会考虑

**Comment by jokester** [comment]
@lijinpei ss-libev 在docker中默认也可以连到host及其LAN，如果ss-go没有特殊处理可能也是。

可以在容器内改了iptable再exec ss，如 [entry.sh](https://github.com/jokester/Dockerfiles/blob/42b828073b3d12dc498b2ebc3ad6d3547d3be5c3/shadowsocks-libev/entry.sh#L5-L13)
