### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by Lewin671** [shadowsocks/shadowsocks-go#466]
运行的时候出现下面这个错误如何解决？

2019/02/27 17:24:12 socks handshake: socks version not supported
2019/02/27 17:24:12 socks handshake: socks version not supported
2019/02/27 17:24:12 socks handshake: socks version not supported
2019/02/27 17:24:12 socks handshake: socks version not supported

**Comment by arthurkiller** [comment]
use socks5 proxy instead

**Comment by Lewin671** [comment]
> use socks5 proxy instead

I use socks5 proxy in firefox, but when I visit any website, the terminal will prompt the above issues.

**Comment by arthurkiller** [comment]
I'm not sure what exactly happened, mostly caused by socks version not pair. Maybe you can try go-shadowsocks2 instead.
