### ISSUE TITLE
Specify server bind interface

### ISSUE THREAD

**Issue by rsanden** [shadowsocks/shadowsocks-go#50]
It seems `shadowsocks-server` binds to all interfaces (`0.0.0.0`).

```
{
    "server":"123.123.123.123",
    "server_port":17777,
}
```

But:

```
root@MyMachine:~# lsof -i :17777
COMMAND     PID  USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
shadowsoc 10333 me    3u  IPv4 3665407420      0t0  TCP *:17777 (LISTEN)
```

I expected this:

```
TCP 123.123.123.123:17777 (LISTEN)
```

Is there a config setting for the server-side bind IP? If not, maybe I can add it and send a pull request. Do you have a suggested implementation?

**Comment by nielspeen** [comment]
@rsanden did you manage to fix this?

@lixin9311 I have to ask, what is the real purpose of the "server" option? Is it ignored completely?

**Comment by rsanden** [comment]
@nielspeen I just changed `net.Listen("tcp", ":"+port)` to `net.Listen("tcp", "1.2.3.4:"+port)`.

From my (limited) understanding, the real purpose of the "server" option here is so that Shadowsocks can use an identical config file on the server-side and local-side, for convenience. I really like that design concept. Using "Server" as the bind interface on the server-side would break that parallelism for anyone using `0.0.0.0` explicitly.

Therefore, I didn't fix it and make a pull request, because it changes behavior and I am not sure what most people want. In my case, I have several interfaces on my server, and I only want Shadowsocks to bind to one of them. But `0.0.0.0` is quite likely a more reasonable default.

What do you think?

The right answer might be a different approach altogether, such as a new "`Interface`" or "`Bind`" option in the json file, which the Client ignores completely. It can be optional, and default to "`0.0.0.0`". This would preserve parallelism but still allow the interface to be specified without hacking the source code.

That's a design decision, which is up to @cyfdecyf, not me.

**Comment by nielspeen** [comment]
@rsanden thank you for the detailed reply. Being able to use the same config on both ends is an nice concept indeed. 

That said, if you insist on keeping the config file the same, your clients will always be connecting to one specific IP only. Listening to 0.0.0.0 in that particular scenario seems unnecessary.

Either solution will work for me though. For now I'll change the Listen statement as per your suggestion.
