### ISSUE TITLE
socks handshake: socks version not supported

### ISSUE THREAD

**Issue by damnhe** [shadowsocks/shadowsocks-go#52]
socks handshake: socks version not supported

fedora21 x64

**Comment by lixin9311** [comment]
Only socks5 is supported.

damnhe <notifications@github.com>于2015年1月12日星期一写道：

**Comment by damnhe** [comment]
of course , the shadowsocks server supports socks5 ,i can connect it by  using shadowsocks-csharp on windows.  It seems that shadowsocks-go doesn't work on fedora

**Comment by lenovo-me** [comment]
shadowsocks-csharp has a built-in polipo to covert socks5 proxy to http proxy.
shadowsocks-csharp=shadowsocks(or shadowsocks-go/shadowsocks-libev...)+polipo+gfwlist2pac
so you need manual installation of polipo on fedora.
