### ISSUE TITLE
shadowsocks-go/shadowsocks下的测试无法编译了

### ISSUE THREAD

**Issue by defia** [shadowsocks/shadowsocks-go#53]
encrypt_test.go:160: ci.newBlock undefined (type *cipherInfo has no field or method newBlock)
然后看了一下代码没看懂怎么改。。。

**Comment by lixin9311** [comment]
你怎么build的 怎么能build test去了

**Comment by defia** [comment]
....我意思就是 go test在build阶段失败了。。。。
不过已经改好了
https://github.com/shadowsocks/shadowsocks-go/pull/54
