### ISSUE TITLE
有支持salsa20/chacha20的计划和时间表吗？

### ISSUE THREAD

**Issue by CNMan** [shadowsocks/shadowsocks-go#55]
谢谢！

**Comment by lixin9311** [comment]
好几个月都没一点动静了 你猜呢

lenovo-me <notifications@github.com>于2015年1月13日星期二写道：

**Comment by lixin9311** [comment]
golang下如果官方不出面很难有支持的，即使有性能也没AES好。
因为AES有硬件加速支持的，而chacha20没有，靠的是用汇编指令才获得评测中的好成绩。
salse20貌似是有官方库。虽然现在有人在golang实现chacha20，不过也是调用了cgo，这样就没有移植性了，如果用纯go语言写，又因为go runtime，性能还不如aes，所以没有必要在golang上实现chacha20。
再说加密计算速度又不是限制你网速的瓶颈，瓶颈大多数还是你的网络带宽，没有必要去玩chacha20，除非你有信仰

**Comment by cyfdecyf** [comment]
其他加密方法如果有纯的 Go 实现的话会考虑加入。如 @lixin9311 所说，引入 cgo 之后跨体系结构和系统的支持就难做了。

**Comment by defia** [comment]
https://github.com/codahale/chacha20
这里有个pure go的chacha20实现，我回头测试一下性能，估计是不会有aes好的。。

**Comment by defia** [comment]
PASS
BenchmarkRC4Init-8	  200000	      8180 ns/op
BenchmarkAES128Init-8	  300000	      3930 ns/op
BenchmarkAES192Init-8	  300000	      4193 ns/op
BenchmarkAES256Init-8	  300000	      4826 ns/op
BenchmarkBlowFishInit-8	   20000	     57403 ns/op
BenchmarkCast5Init-8	   30000	     57369 ns/op
BenchmarkDESInit-8	  300000	      5053 ns/op
BenchmarkRC4MD5Init-8	  200000	      8710 ns/op
BenchmarkChaCha20Init-8	 1000000	      1044 ns/op
ok  	_/D_/shadowsocks-go/shadowsocks	14.824s

试了下chacha20，确实快不少。与shadowsocks-libev互通成功。
上述chacha20包封装的很标准，所以改起来也很简单，但是因为引入了unsafe包，具体要不要加入，由cyfdecyf决定吧

**Comment by defia** [comment]
https://godoc.org/golang.org/x/crypto/salsa20
然后看上去salsa20也在进入准官方库的过程中。不过现在的封装跟标准库不太一样。。
