### ISSUE TITLE
Client bind interface

### ISSUE THREAD

**Issue by xnoreq** [shadowsocks/shadowsocks-go#59]
local_address in config.json is ignored, as is the command line option -b="" (for bind I guess).

**Comment by 321cyb** [comment]
In client, local_address in config.json is ignored, while command line option -b is respected.
What problem do you have?

**Comment by xnoreq** [comment]
Oh yeah I'm sorry, `-b` works. The tool I used resolved 127.0.0.1 to the host name so I wrongly assumed it was not bound to localhost.
