### ISSUE TITLE
write function doesn't use correctly

### ISSUE THREAD

**Issue by damnhe** [shadowsocks/shadowsocks-go#60]
hi,
   After i have read the code , i think there may be exists a bug becasue write function does't use correctly.
    In the pipe.go line 38 . As we know,  the length  write function return which it's truely have been wirtten   to the stream.
   			if _, err = dst.Write(buf[0:n]); err != nil {
				Debug.Println("write:", err)
				break
			}

but this code doesn't use it . We can slove this problem use a loop 

			var sum, write = 0, 0
			for sum < n {
				write, err = dst.Write(buf[sum:n])
				sum += write
				if err != nil {
					Debug.Println("write:", err)
					break
				}
			}

i hope it's useful
thanks!

**Comment by cyfdecyf** [comment]
I don't remember the reason why I do not check the written bytes.

Maybe I mistaken [`File.Write`](https://golang.org/pkg/os/#File.Write)'s doc for `TCPConn.Write`. Or maybe I thought it should also confirm to the [`io.Writer`](https://golang.org/pkg/io/#Writer) interface. Both of these two `Write` return a non-nil error if it returns n < len(p).

It would be awkward to use loop for every socket write, but I am not sure `TCPConn.Write` has the same guarantee now ...

I'll have further check on this issue.

**Comment by lixin9311** [comment]
http://golang.org/src/net/fd_unix.go?h=Write#L317
line 331
if nn == len(p) {
break
}
If the write operation succeeds the n that TCPConn.Write returns should be equal to len(buf), otherwise a Non-nil err should be returned.
I think Google has already implemented the loop.

**Comment by cyfdecyf** [comment]
Thanks @lixin9311 for pointing this out.

I was actually reading the `Write` function when posting the last reply, and should have read the function before when I tried to port Go's net package to Lua in [luanet](https://github.com/cyfdecyf/luanet/blob/master/fd_unix.lua#L182). But I just ignored the loop, symptom for working for too long these days ...

For future reference, I'll include the write function here.

``` go
func (fd *netFD) Write(p []byte) (nn int, err error) {
	if err := fd.writeLock(); err != nil {
		return 0, err
	}
	defer fd.writeUnlock()
	if err := fd.pd.PrepareWrite(); err != nil {
		return 0, &OpError{"write", fd.net, fd.raddr, err}
	}
	for {
		var n int
		n, err = syscall.Write(int(fd.sysfd), p[nn:])
		if n > 0 {
			nn += n
		}
		if nn == len(p) {
			break
		}
		if err == syscall.EAGAIN {
			if err = fd.pd.WaitWrite(); err == nil {
				continue
			}
		}
		if err != nil {
			n = 0
			break
		}
		if n == 0 {
			err = io.ErrUnexpectedEOF
			break
		}
	}
	if err != nil {
		err = &OpError{"write", fd.net, fd.raddr, err}
	}
	return nn, err
}
```
