### ISSUE TITLE
Ubuntu下面有deb包或PPA源吗?

### ISSUE THREAD

**Issue by sabersalv** [shadowsocks/shadowsocks-go#61]
使用Ubuntu的服务器下, 用`apt`来安装和管理更加方便.

**Comment by sabersalv** [comment]
关掉能给个理由吗?

**Comment by cyfdecyf** [comment]
源代码目录里有个 deb 目录，也有[脚本](script/createdeb.sh)可以创建 deb 包，需要的话可以自己创建。

deb 打包我其实不熟悉，创建的包或许存在各种各样的问题，所以放弃了。

**Comment by sabersalv** [comment]
多谢. 有时间我来打包一个.

**Comment by ElvizLai** [comment]
试试docker吧，自己在用，目前测试非常稳定。
