### ISSUE TITLE
Please use new import path

### ISSUE THREAD

**Issue by empirefox** [shadowsocks/shadowsocks-go#64]
When building with golang1.4, it requires "golang.org/x/crypto/blowfish" but not "github.com/golang/crypto/blowfish".
Here: https://github.com/golang/crypto/blob/master/blowfish/cipher.go#L6
Can you fix this?
Thanks!

**Comment by ddatsh** [comment]
wtf,本来我提交 pr #63是为了让下载/编译时不要再用hg 去clone googlecode的那份代码
1.4的编译机制有啥区别呢

**Comment by empirefox** [comment]
Great, thank you very much!
