### ISSUE TITLE
似乎只能监听ipv6。。。

### ISSUE THREAD

**Issue by molisoft** [shadowsocks/shadowsocks-go#67]
不管在哪台服务器上启动。。都只能监听ipv6。。。IPV4木有。。。

**Comment by 321cyb** [comment]
请问你是怎么得出这个结论的呢？

如果你用netstat看不到ipv4的socket，那是因为Linux上ipv6的socket本身就有处理ipv4的能力，关键词 ipv4 mapped ipv6 address 和  IPV6_V6ONLY。 而golang在双栈环境下是更倾向于用这种处理方式的，可以看 http://golang.org/src/net/ipsock_posix.go 里的 probeIPv6Stack 和 favoriteAddrFamily

**Comment by molisoft** [comment]
我是用的命令 
lsof -i:端口
我记得刚开始的时候，会显示2条数据，一个ipv4, 一个是ipv6 
但是后来就只有一条ipv6了

**Comment by 321cyb** [comment]
lsof 也一样的，原因就是我上面说的那样，ipv6 socket有handle ipv4 的能力。
