### ISSUE TITLE
Shadowsocks server stops working randomly

### ISSUE THREAD

**Issue by nodje** [shadowsocks/shadowsocks-go#74]
It happens very rarely (once every few months, with ~10 active clients), but sometimes all clients suddenly stop being able to get traffic.
It's still running on the server but it's not serving request anymore.

A restart of the process solves the problem instantly.

Does anyone have the same problem? What additional test could I run when it happens to understand where the problem comes from?

I have it installed on Ubuntu.

PS: I put it on the go version since it's the version I use but might well be a general Shadowsocks problem.

**Comment by defia** [comment]
how did you install shadowsocks-go?
a pre-compiled binary or manually build from source?

**Comment by nodje** [comment]
I'm still running go1.2.1 linux/386, originally compiled shadowsocks-server-1.1.1 form source, but replaced it recently with a pre-compiled 1.1.3 binary.

In which way would it make a difference?

**Comment by defia** [comment]
go 1.2.1 is too old.
does a pre-compiled binary fix your issue?
i think maybe you should use go 1.4.1 to build shadowsocks-go or at least go 1.3.3.
i find that pre-compiled binaries were released on sep.28 2014, when go 1.3.3 has not been released at that time.

**Comment by nodje** [comment]
So your advice would be get the latest Go version and compile latest shadowsocks with it? 
I'll do that, cannot harm, and I'll keep this issue posted.

**Comment by lixin9311** [comment]
No further information received. Close.
