### ISSUE TITLE
http://dl.chenyufei.info/shadowsocks/ 目录的组织能不能提供个-latest方便wget最新版

### ISSUE THREAD

**Issue by coldwinds** [shadowsocks/shadowsocks-go#75]
比如

http://dl.chenyufei.info/shadowsocks/shadowsocks-server-linux64-latest.gz

这样方便在不用得知版本的情况下下载最新版

**Comment by lixin9311** [comment]
go get -u github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-server
go get -u github.com/shadowsocks/shadowsocks-go/cmd/shadowsocks-local

**Comment by cyfdecyf** [comment]
后面发布新版本的时候会考虑 @coldwinds 的建议，希望能在一个月内发个新版本出来。
