### ISSUE TITLE
PipeThenClose的一个问题

### ISSUE THREAD

**Issue by defia** [shadowsocks/shadowsocks-go#76]
// PipeThenClose copies data from src to dst, closes dst when done.
	func PipeThenClose(src, dst net.Conn, timeoutOpt int) {
		defer dst.Close()
		buf := pipeBuf.Get()
		defer pipeBuf.Put(buf)
		for {
			if timeoutOpt == SET_TIMEOUT {
				SetReadTimeout(src)
			}
			n, err := src.Read(buf)
			// read may return EOF with n > 0
			// should always process n > 0 bytes before handling error
			if n > 0 {
				if _, err = dst.Write(buf[0:n]); err != nil {
					Debug.Println("write:", err)
					break
				}
			}
			if err != nil {
				// Always "use of closed network connection", but no easy way to
				// identify this specific error. So just leave the error along for now.
				// More info here: https://code.google.com/p/go/issues/detail?id=4373
				/*
					if bool(Debug) && err != io.EOF {
						Debug.Println("read:", err)
					}
				*/
				break
			}
		}
	}

在dst.Write处，是不是用_,err:=dst.Write(buf[0:n])会更好？
现在的代码，如果Read的时候，n>0且返回eof，而Write成功，err会被覆盖为nil，导致循环不break，会进行下一次循环并Read，这时候才会再次eof跳出循环

**Comment by cyfdecyf** [comment]
谢谢指出，的确是个 bug，develop branch 已经修复。
