### ISSUE TITLE
关于多配置文件的服务端调用

### ISSUE THREAD

**Issue by StrollStars** [shadowsocks/shadowsocks-go#78]
Go版本支持多服务器配置，这是一个很大的特点。有人说多服务器配置在连接时是随机挑选一个，但是我测试发现是从上而下匹配，只要第一个有效，就一直用第一个的。可否在下一版本中实现随机调用列表中的任意一个服务器，至少于前一次不同呢？

**Comment by alexwhen** [comment]
最好是加入速度检测，然后再选最快的来建立连接，而不是随机

**Comment by CNMan** [comment]
就是按配置文件中的顺序来的，不是随机

**Comment by alexwhen** [comment]
能否检测速度来做选择？以ping值做判断依据或是其他

**Comment by lixin9311** [comment]
Currently, we do not have such plan, but any contribution is welcome.
