### ISSUE TITLE
Stability problem with radio streaming

### ISSUE THREAD

**Issue by nodje** [shadowsocks/shadowsocks-go#80]
Hi,

just want to feedback an interesting usage:
I'm using SS at home (bad 联通 connection) to connect to a server in Europe for quite a couple of years now and always had problem when streaming radio from abroad China. Stream would cut every 5mns and not recover by itself.

A couple days ago I had to switch back to SSH (to the exact same server) for some reason and realize that I can get a stable radio streaming now.

Could it be a problem in the protocol itself? Of course, I don't have the problem with good connections in general.

Also, I just realize doing some test with speedtest.net that using Privoxy in front of SS is significantly faster than direct SS. And it's filtering bad stuff. 
I highly recommend this setup!

**Comment by Provissy** [comment]
Try use AES-256-CFB encryption.
GFW is strong now xD

**Comment by nodje** [comment]
Ouch, just switched back from 256 to AES-128-CFB a month ago when I read somewhere that it was just enough... not an easy switch now, too many clients...

Do you really think it could make a difference? I mean, appart from the streaming, I can surely access any resources without problem (just not in a stable manner as the connection is so weak). 
What about default port? Would changing it make any difference? I just can't believe GFW would be tricked by a simple port change.

@Provissy is it a coincidence your name rhyme with Privoxy? :P

**Comment by Provissy** [comment]
:DDD
hmmm, i always use ports higher than 20000.
seems no big problems

**Comment by a1328788808** [comment]
GFW对于长时间连接并无法识别的流量，轻则劣化你的线路，重则直接掐断。你更换端口以后会明显改善，所以请尝试配置多端口，每个client尽量用不同的端口。每个端口对应的加密方式也可以不一样。推荐RC4-MD5。

**Comment by Provissy** [comment]
如楼上所说，建议使用20000+端口，但是即使这也可能会被临时切断一分钟左右，这个谁都救不了。。。

**Comment by nodje** [comment]
@a1328788808 我试一试更换端口。用多端口.
但是更换端口以后，GFW不是还会发现时间连接并无法识别的流量？
为什么推荐RC4-MD5? 我以为AES-xxx-CFB是最强的？

**Comment by ElvizLai** [comment]
@nodje 与加密强度没有关系。
GFW的规则是只要不能解密，就判断你的内容非法。然后就干扰你。
使用RC算法的原因是因为对于小型vps，速度上会好些。

**Comment by nodje** [comment]
嗯，明白了。其实RC4-MD5对小型路由器可能刚有效果。
@ElvizLai 你确定GFW的规则是不能加密？是不是要看哪一种加密连接？加入HTTPS应该不会干扰。
我感觉为了连接国外的资源用加密经常是刚快的。

**Comment by Provissy** [comment]
HTTPS和Shadowsocks就不沾边了。
GFW规则是无法解密。

**Comment by dearplain** [comment]
shadowsocks是多tcp连接的，一段时间内连接太多，会被干扰

**Comment by dearplain** [comment]
你可以改到80端口试试，我改后下载很稳定了。

**Comment by lixin9311** [comment]
No further information received. Close.
