### ISSUE TITLE
看介绍有流量统计功能。

### ISSUE THREAD

**Issue by gzw13999** [shadowsocks/shadowsocks-go#84]
请问流量统计功能最终统计到哪去了？以及相关代码在哪也没找到。
另外还要请教下，流量限制功能如何实现呢？

**Comment by lixin9311** [comment]
有么？我都没见过介绍

**Comment by ElvizLai** [comment]
@gzw13999 https://github.com/ElvizLai/shadowsocks-go-with-traffic-limits 开始学go的时候简单的实现过一个。代码比较糙，实现起来也略粗暴。

**Comment by cyfdecyf** [comment]
没有这个功能，可以考虑从 conn.go 中加流量统计代码。
