### ISSUE TITLE
addr type 224 not supported

### ISSUE THREAD

**Issue by guotie** [shadowsocks/shadowsocks-go#85]
版本1.1.3

go： 1.4.2

服务端：linux
客户端：windows

**Comment by guotie** [comment]
addr type 206 not supported

**Comment by lixin9311** [comment]
大概是你密码 或加密方式没对上

**Comment by genzj** [comment]
有可能是@lixin9311 说的密码相关问题。
还有一个可能是端口上有杂包（嗅探之类）。可以尝试更换别的服务器端口。

**Comment by guotie** [comment]
我发现配置多个host的时候会出现这个问题。
