### ISSUE TITLE
客户端配置连结多个服务器的具体方法是什么呢?

### ISSUE THREAD

**Issue by wonderbeyond** [shadowsocks/shadowsocks-go#88]
我搜遍了文档和第三方资料都没有看到具体的介绍, 但是我试着配置成功了：

``` json
{
    "server": ["x.x.x.x","y.y.y.y"],
    "server_port": 8388,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "FvCkGFW_oops",
    "timeout": 300,
    "method": "aes-128-cfb",
    "fast_open": false
}
```

这样配置是可行的，两个服务器停掉任何一个客户端都可以正常工作。
但是我在官方文档和例子中没有找到是否应该这样弄, 我如果还要针对不同的服务器区分端口、算法和密码等配置呢？

**Comment by CNMan** [comment]
你理解有误，不是同时连多个服务器，而是第一个不行第二个，第二个不行第三个...

**Comment by wonderbeyond** [comment]
@CNMan 多谢提示！
我测试了，运行中会动态的尝试连结不同的服务器，不仅仅是在启动的时候绑定。
我临时关掉其中任何一个server，本地的socks服务都OK。

**Comment by CNMan** [comment]
按json中的顺序连，连接失败 才 去连接下一个

**Comment by WangZhengmao** [comment]
我用这个方法配置成功了，但是使用https://github.com/shadowsocks/shadowsocks-go/blob/master/sample-config/client-multi-server.json的方法配置不成功，因为我使用了ipv6地址的服务器总是提示有多余的冒号。
请问我如何配置多个服务器（包含ipv6)并且配置单独的密码呢？
