### ISSUE TITLE
为什么我升级1.1.4以后电脑可以使用ss，但是手机上就用不了了？

### ISSUE THREAD

**Issue by calsc** [shadowsocks/shadowsocks-go#89]
我升级了1.1.4，电脑能连上，手机上选择全局才可以使用，选择绕过局域网及中国大陆地址就不能用了？我另外一个服务器上用1.1.3是没问题的。

**Comment by calsc** [comment]
我用别手机试了 还是这样的 选择绕过局域网及中国大陆地址就不能用

**Comment by cyfdecyf** [comment]
你的手机上的 shadowsocks 客户端是哪个，代理配置跟电脑上的一样么？

**Comment by calsc** [comment]
手机客户端是安卓的，版本2.6.6  2.6.5我都试过，配置是一样的，我升级了1.1.4服务端后，手机上选择全局才可以使用，选择绕过局域网及中国大陆地址就不能用，用1.1.3服务端时是没问题的。

**Comment by calsc** [comment]
@cyfdecyf

**Comment by defia** [comment]
你这个完全不像是服务器端的问题。。。

**Comment by jazychou** [comment]
你是不是在手机端勾选了一次性认证这个试验性功能？把这个关掉试试。我今天也搞了半天，最后发现是这个开开了的原因。

**Comment by helloworld-du** [comment]
我也碰到相同的问题了，手机一升级就不能用了，pc和服务器用的都是go的版本。看服务器端日志一直报错。服务器端改配置中的加密方法项不管用，改客户端的为aes-128-cbf才不报错。但是不管服务器改成什么加密方式，pc都能访问（pc加密一直没动过），android都不能访问。后台也没看到日志有报错

**Comment by lixin9311** [comment]
@helloworld-du 有没有勾选了一次性认证？你是通过什么方式更改加密方法的？

**Comment by zaaack** [comment]
我也是这样。。

**Comment by bigtan** [comment]
@zaaack 仔细检查服务端是不是开了one time auth，如果服务端没有开，则是兼容模式，客户端可开可不开；如果服务端开了，则客户端必须开。另外，仔细检查加密方式和密码。

**Comment by littlewrite** [comment]
我用的Android4.4.4, shadowsocks 3.2.7. 之前用的好好的，能上。后来不知改了啥，就gg了。PC端能上，后来我把设置改成
一次认证： off.
路由： 全局
UDP转发：off
就又可以用了。
亲测可用！

**Comment by bigtan** [comment]
@littlewrite 
shadowsocks-go不支持udp

**Comment by littlewrite** [comment]
@bigtan 
我用的 shadowsocks-python android 其他不懂哈。
