### ISSUE TITLE
希望支持tcp fast open~

### ISSUE THREAD

**Issue by leafonsword** [shadowsocks/shadowsocks-go#90]
tcp fast open能大大减小延迟，希望尽快支持此特性~

**Comment by LazyZhu** [comment]
https://github.com/bradleyfalzon/tcp-fast-open

**Comment by jzp820927** [comment]
同样希望 shadowsocks-go 能支持 tcp fast open，2楼的项目，没看懂要怎么用

**Comment by genzj** [comment]
可以尝试一下PR #101

**Comment by lixin9311** [comment]
golang/go#4842
Waiting for official support.
