### ISSUE TITLE
Different encryption method per user

### ISSUE THREAD

**Issue by nielspeen** [shadowsocks/shadowsocks-go#91]
Is it possible to let different users use different encryption methods? Some of my users want to switch to the newly added Chacha20 while others prefer to stay with AES-128.

Currently the config file makes you switch the entire server at once.

**Comment by ElvizLai** [comment]
Try docker!  One user can has it's own config.

**Comment by nielspeen** [comment]
Running multiple processes doesn't require docker. The problem is that running multiple processes is not a scalable solution. We have 10.000+ users.

**Comment by ElvizLai** [comment]
It's easy to modify source `server.go` to fulfill your feature. I tried and it works well.
 I will try to add an implement of traffic limit.

**Comment by cyfdecyf** [comment]
@ElvizLai would you like to contribute your improvement to shadowsocks-go?

**Comment by ElvizLai** [comment]
@cyfdecyf  I modified the server.go and I delete some unnecessary features for me like pwdUpdate. And it now must using config.json to start server. Maybe It's not OK for 10.000+ users.

**Comment by cc2001** [comment]
@ElvizLai could you show us what you changed anyway? Maybe on your own branch/repo? I'm trying to do the same thing and would like to see how you did it :)
