### ISSUE TITLE
socks handshake: socks version not supported  error

### ISSUE THREAD

**Issue by marksnoopy** [shadowsocks/shadowsocks-go#92]
when i start the shadowsocks-local , print below:

2015/06/09 09:39:07 socks handshake: socks version not supported
2015/06/09 09:39:07 socks handshake: socks version not supported
2015/06/09 09:39:07 socks handshake: socks version not supported
2015/06/09 09:39:07 socks handshake: socks version not supported
2015/06/09 09:39:08 socks handshake: socks version not supported
2015/06/09 09:39:09 socks handshake: socks version not supported
2015/06/09 09:39:09 socks handshake: socks version not supported
2015/06/09 09:39:10 socks handshake: socks version not supported
2015/06/09 09:39:10 socks handshake: socks version not supported
2015/06/09 09:39:12 socks handshake: socks version not supported

my start command is ./shadowsocks-local-linux64-1.1.3 -s xxxx -p xxxx -b xxxx -l 1080 -k xxxx -m aes-256-cfb

**Comment by cyfdecyf** [comment]
1. Check password matches on client and server
2. Check the client using shadowsocks-local specifies socks 5 proxy
3. If you can use shadowsosks, but still seeing these messages, maybe there's some program scanning open ports on your system

**Comment by marksnoopy** [comment]
thanks  and i had solved the problem

**Comment by isaacselement** [comment]
@marksnoopy  How did you solved the problem? I got the issue to ~~~~~~  thanks in advance.

**Comment by marksnoopy** [comment]
@isaacselement  because safari  do not support socks but socks5 .
