### ISSUE TITLE
Windows版shadowsocks-local报错

### ISSUE THREAD

**Issue by deathrush** [shadowsocks/shadowsocks-go#93]
2015/07/09 09:48:16 error getting request: socks command not supported
2015/07/09 09:48:52 error getting request: socks command not supported
2015/07/09 09:48:56 error getting request: socks command not supported
2015/07/09 09:54:11 error getting request: socks command not supported

**Comment by genzj** [comment]
配置了SS代理的应用软件是什么？能否上一张其代理配置界面的截图？

**Comment by devfighter** [comment]
chrome45，命令行显示提示
~~~
2015/09/24 15:32:59 starting local socks5 server at :1080 ...
。。。
2015/09/24 15:43:37 socks handshake: socks version not supported
~~~

**Comment by ssoor** [comment]
同遇到,
用SwitchyOmega设置的代理,但是同事使用没有问题.
应该和Chrome的版本有关.目前转换成http代理在使用.无问题.
